In [1]:
%pip install tableone
import pandas as pd
from tableone import TableOne
import warnings

#import ace_tools as tools
warnings.filterwarnings("ignore")
pd.set_option('display.max_rows', 200)  # Set to 200 or more, higher than 105
pd.set_option('display.max_columns', None)  # Show all columns if needed

Requirement already satisfied: tableone in c:\users\hibaa\documents\github\alert-fatigue\hiba_env\lib\site-packages (0.9.5)
Requirement already satisfied: jinja2>=3.1.4 in c:\users\hibaa\documents\github\alert-fatigue\hiba_env\lib\site-packages (from tableone) (3.1.6)
Requirement already satisfied: numpy>=1.19.1 in c:\users\hibaa\documents\github\alert-fatigue\hiba_env\lib\site-packages (from tableone) (2.1.3)
Requirement already satisfied: openpyxl>=3.1.2 in c:\users\hibaa\documents\github\alert-fatigue\hiba_env\lib\site-packages (from tableone) (3.1.5)
Requirement already satisfied: pandas>=2.0.3 in c:\users\hibaa\documents\github\alert-fatigue\hiba_env\lib\site-packages (from tableone) (2.3.2)
Requirement already satisfied: scipy>=1.10.1 in c:\users\hibaa\documents\github\alert-fatigue\hiba_env\lib\site-packages (from tableone) (1.15.3)
Requirement already satisfied: statsmodels>=0.14.1 in c:\users\hibaa\documents\github\alert-fatigue\hiba_env\lib\site-packages (from tableone) (0.14.5)
Requirement already satisfied: tabulate>=0.9.0 in c:\users\hibaa\documents\github\alert-fatigue\hiba_env\lib\site-packages (from tableone) (0.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\hibaa\documents\github\alert-fatigue\hiba_env\lib\site-packages (from jinja2>=3.1.4->tableone) (3.0.2)
Requirement already satisfied: et-xmlfile in c:\users\hibaa\documents\github\alert-fatigue\hiba_env\lib\site-packages (from openpyxl>=3.1.2->tableone) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hibaa\documents\github\alert-fatigue\hiba_env\lib\site-packages (from pandas>=2.0.3->tableone) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hibaa\documents\github\alert-fatigue\hiba_env\lib\site-packages (from pandas>=2.0.3->tableone) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hibaa\documents\github\alert-fatigue\hiba_env\lib\site-packages (from pandas>=2.0.3->tableone) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hibaa\documents\github\alert-fatigue\hiba_env\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.3->tableone) (1.17.0)
Requirement already satisfied: patsy>=0.5.6 in c:\users\hibaa\documents\github\alert-fatigue\hiba_env\lib\site-packages (from statsmodels>=0.14.1->tableone) (1.0.1)
Requirement already satisfied: packaging>=21.3 in c:\users\hibaa\documents\github\alert-fatigue\hiba_env\lib\site-packages (from statsmodels>=0.14.1->tableone) (25.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
#TODO: Load the data: df_main_active_adult.csv, this order level data only active adults
#df_main_active_adult = pd.read_csv('alert_analysis/data/main_data_2022/df_main_active_adult_renamed.csv')
df_main_active_adult = pd.read_csv(r'C:\Users\hibaa\Documents\GitHub\alert-fatigue\alert_analysis\data\main_data_2022\df_main_active_adult_renamed_new_clean_sample_100pct.csv')
print(df_main_active_adult.shape)
df_main_active_adult.head(10)

(2477205, 167)

,hospital_code,hospital_name,unit_category,severity_level_to_stop_order,medical_record,admission_num,age,gender,sector,time_prescribing_order,alert_drug_header,module_alert_rn,alert_message,alert_severity,order_origin,shift_type,day,currently_hospitalized,num_med_order,response_reasons_other_text,response_type,order_details,drug_name_order,chronic_diagnosis,hospital_diagnosis,id1,id2,alert_rn_severity,response_reasons_codes,response_reasons__selected_text,module_severity_rn,mabat_request_time_ms,mabat_response_time_ms,response_time,dosing_subgroup,neodosing_subgroup,dosing_frequency_direction,dosing_single_dose_direction,dosing_max_daily_dose_direction,neo_dosing_frequency_direction,neo_dosing_single_dose_direction,neo_dosing_max_daily_dose_direction,atc_count,drug_atc,chronic_drug_count,drug_order_id,medication_orders_hospitalization,diagnosis_count,disease_split,num_of_chronic_diagnosis,liver_count,hepatic_count,cirrhosis_count,hepatitis_count,portal_hypertension_count,jaundice_count,myocardial_count,heart_failure_count,peripheral_vascular _disease_count,pvd_count,cerebrovascular_count,stroke_count,cerebral_infarction_count,tia_count,cva_count,dementia_count,chronic_ pulmonary _disease_count,copd_count,chronic _obstructive _pulmonary _disease_count,rheumatic_disease_count,fibromyalgia_count,gout_count,arthritis_count,ankylosing_spondylitis_count,scleroderma_count,duodenal_ulcer_count,peptic_ulcer_count,gastric_ulcer_count,diabetes_count,hemiplegia_count,hemiparesis_count,paraplegia_count,renal_count,pyelonephritis_count,hemodialysis_count,kidney_count,ckd_count,arf_count,aki_count,malignancy_count,malignant_count,carcinoma_count,neoplasm_count,adenocarcinoma_count,leukemia_count,aml_count,cml_count,lymphoma_count,hiv_count,metastatic_count,metastasis_count,liver_group_count,pvd_group_count,cerebrovascular_group_count,copd_group_count,gout_group_count,ulcer_group_count,hemiplegia_group_count,renal_group_count,malignancy_group_count,leukemia_group_count,metastatic_group_count,charlson_score,charlson_score_age_adj,survival_rate_10y_age_adj,age_group,age_category,drugs_in_alert_message,alerts_per_order_count,allergy,ddi_contraindicated_severity,ddi_moderate_severity,ddi_severe_severity,dosing,technical_alerts,renal_alerts,neo_dosing,chronic_med_count,date_time_prescribe,hospital_days,diff_time_mabat_y,dosing_duration,dosing_frequency,dosing_max_daily_dose,dosing_message,dosing_single_dose,neo_dosing_duration,neo_dosing_frequency,neo_dosing_max_daily_dose,neo_dosing_message,neo_dosing_single_dose,alert_type,alert_status,atc_group,atc_group_ud,prescription_day,chronic_med_ud,hospital_category,unit_category_ud,kidney_disease,hepatic_disease,diabetes_disease,ischemic_heart_disease,copd_disease,cerebrovascular_disease,peptic_ulcer_disease,dementia_disease,oncological_disease,hemato_oncological_disease,hypertension_disease,atrial_fibrillation_disease,hyperlipidemia_disease,congestive_heart_failure_disease,obesity_disease,response_type_ud,alert_type_binary,alert_status_binary
0,26,EMEK,Emergency,Active Mode,3471471,2.022093e+09,20.0,FEMALE,DOCTOR,2022-08-28T21:18:37Z,NaN,NaN,NaN,NaN,Medication Order,afternoon,Sunday,0,3,NaN,Non_alert,IntraVenous PERFALGAN 1000 mg Once,PERFALGAN,NaN,NaN,205232,410.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,N02BE01,0,26_19929615,3,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,98.30,adult,19-30,NaN,0.0,0,0,0,0,0,0,0,0,0,2022-08-28,1,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert,ANALGESICS,ANALGESICS,WEEKDAY,0,Medium hospital,Emergency,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,No_response_need,0.0,0.0
1,20,BELINSON,Internal,Active Mode,11258263,2.022142e+09,81.0,FEMALE,DOCTOR,2022-08-16T11:05:38Z,NaN,NaN,NaN,NaN,Medication Order,morning,Tuesday,44,13,NaN,Non_alert,IntraVenous OPTALGIN 1000 mg <br/>SODIUM CHL...,"OPTALGIN,SODIUM CHLORIDE 0.9%",CVA = Cerebrovascular accid...,DYSLIPIDEMIA;HYPERTENSION;Ischemic heart disease,123771,2840.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,N02BB02,0,20_24526887,13,3,"['DYSLIPIDEMIA', 'HYPERTENSION', 'ISCHEMIC HEA...",3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,53.39,adult,76-85,NaN,0.0,0,0,0,0,0,0,0,0,7,2022-08-16,3,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert,ANALGESICS,ANALGESICS,WEEKDAY,0,Large hospital,new_internal,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,No_response_need,0.0,0.0
2,24,SOROKA,Internal,Active Mode,9592528,2.022102e+09,84.0,MALE,DOCTOR,2022-11-03T09:59:46Z,Aspirin Cardio 100 mg Enteric Coated Tablet,DDI - 1,ASPIRIN BAYER and PREDNISONE may interact base...,Moderate Interaction,Medication Order,morning,Thursday,29,9,NaN,Non_stopping_alert,"Oral PREDNISONE 15 mg X1 Per Day, Every Da...",PREDNISONE,NaN,"CHRONIC ISCHEMIC HEART DISEASE, UNSPECIFIED;HE...",116396,909.0,DDI-Moderate Interaction,NaN,NaN,DDI - Alert Severity 1,2022-11-03 09:58:32.042999744+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,H02AB07,0,24_35206411,15,3,"['CHRONIC ISCHEMIC HEART DISEASE, UNSPECIFIED'...",0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,2,6,2.25,adult,76-85,"ASPIRIN,PREDNISONE",1.0,0,0,1,0,0,0,0,0,0,2022-11-03,2,NaN,0,0,0,0,0,0,0,0,0,0,Non_Error_alert,Non_stopping_alert,CORTICOSTEROIDS FOR SYSTEMIC USE,OTHER,WEEKDAY,0,Large hospital,new_internal,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,No_response_need,NaN,NaN
3,24,SOROKA,Gynecology,Active Mode,8784914,2.022024e+09,32.0,FEMALE,NURSE,2022-03-15T06:41:08Z,NaN,NaN,NaN,NaN,Protocol,night,Tuesday,37,2,NaN,Non_alert,Protocol: OTC<br/>Oral OPTALGIN 500 mg Once,OPTALGIN,NaN,NaN,198868,5912.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,N02BB02,0,24_32666801,3,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,98.30,adult,31-44,NaN,0.0,0,0,0,0,0,0,0,0,0,2022-03-15,2,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert,ANALGESICS,ANALGESICS,WEEKDAY,0,Large hospital,OTHER,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,No_response_need,0.0,0.0
4,23,KAPLAN,Internal,Active Mode,4207533,2.022013e+09,80.0,MALE,DOCTOR,2022-04-19T11:00:56Z,NaN,NaN,NaN,NaN,Protocol,morning,Tuesday,24,23,NaN,Non_alert,Protocol: 1סכרת אינסולין -BASAL BOLUS<br/>SubC...,INSULIN APIDRA,COVID-19 INFECTION;PERTROCHANTERIC FRACTURE OF...,Aortic Regurgitation;Aortic Valve Transcathete...,69731,3388.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,A10AB06,0,23_14721779,49,20,"['AORTIC REGURGITATION', 'AORTIC VALVE TRANSCA...",3,0,0,0,0,0,0,2,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,10,14,0.00,adult,76-85,NaN,0.0,0,0,0,0,0,0,0,0,0,2022-04-19,11,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert,DRUGS USED IN DIABETES,DRUGS USED IN DIABETES,WEEKDAY,0,Medium hospital,new_internal,1,0,1,1,0,1,0,0,0,0,1,0,1,1,0,No_response_need,0.0,0.0
5,20,BELINSON,Internal,Active Mode,11743390,2.022158e+09,75.0,MALE,DOCTOR,2022-12-21T14:09:11Z,NaN,NaN,NaN,NaN,Medication Order,morning,Wednesday,47,14,NaN,Non_alert,Naso Gastric Tube PROCOR 600 mg X1 Per Day...,PROCOR,CONGESTIVE HEART FAILURE;CONTINUOUS MECHANICAL...,ANEMIA;CHRONIC RENAL FAILURE;CONGESTIVE HEART ...,24219,3406.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,C01BD01,0,20_25678269,37,7,"['ANEMIA', 'CHRONIC RENAL FAILURE', 'CONGESTIV...",7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,7,10,0.00,adult,65-75,NaN,0.0,0,0,0,0,0,0,0,0,0,2022-12-21,11,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert,CARDIAC THERAPY,CARDIOVASCULAR DRUGS,WEEKDAY,0,Large hospital,new_internal,1,0,1,0,0,0,0,0,0,0,1,0,1,1,0,No_response_need,0.0,0.0
6,24,SOROKA,Cardiology,Active Mode,9618769,2.022105e+09,70.0,MALE,DOCTOR,2022-11-08T20:28:46Z,NaN,NaN,NaN,NaN,Medication Order,afternoon,Tuesday,14,2,NaN,Non_alert,"Oral ASPIRIN BAYER 100 mg X1 Per Day, Ever...",ASPIRIN BAYER,ACUTE NON ST ELEVATION MYOCARDIAL INFARCTION (...,DIABETES MELLITUS;DYSLIPIDEMIA;HYPERTENSION ES...,125111,1885.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,B01AC06,0,24_35265337,13,7,"['DIABETES MELLITUS', 'DYSLIPIDEMIA', 'HYPERTE...",13,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,5,8,0.00,adult,65-75,NaN,0.0,0,0,0,0,0,0,0,0,0,2022-11-08,1,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert,ANTITHROMBOTIC AGENTS,ANTITHROMBOTIC AGENTS,WEEKDAY,0,Large hospital,OTHER,1,0,1,0,0,1,0,0,0,0,1,0,1,0,0,No_response_need,0.0,0.0
7,19,YOSEFTAL,Surgery,Active Mode,777931,2.022005e+09,67.0,FEMALE,DOCTOR,2022-09-04T14:59:17Z,Sodium Chloride 0.9 % Intravenous Injection 50...,DRC - Message 1,Unknown dose unit : cc(ml).,NaN,Protocol,morning,Sunday,2,9,NaN,Ignore,Protocol: ER CHOLECYSTITIS<br/>IntraVenous OPT...,"OPTALGIN,SODIUM CHLORIDE 0.9%",ACUTE CHOLECYSTITIS,NaN,123649,3127.0,Technical alert,104.0,Other - detail,DRC - Message Alert Severity 1,2022-09-04 14:59:50.759999752+00:00,2022-09-04 14:59:54.106999874+00:00,3347.000122,DRC - Message 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,N02BB02,0,19_27447679,12,0,NaN,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,90.15,adult,65-75,NaN,1.0,0,0,0,0,0,1,0,0,0,2022-09-04,3,3347.000122,0,0,0,1,0,0,0,0,0,0,Non_Error_alert,Stopping_alert,ANALGESICS,ANALGESICS,WEEKDAY,0,Small hospital,Surgery,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Ignore,NaN,1.0
8,24,SOROKA,Internal,Active Mode,9006872,2.022045e+09,89.0,FEMALE,DOCTOR,2022-05-20T00:12:21Z,Circadin 2 mg Modified Release Tablet,DDI - 1,CIRCADIN and SERTRALINE TEVA may interact base...,Undetermined Severity - Alternative Therapy In...,Medication Order,night,Friday,30,18,NaN,Non_alert,"Oral SERTRALINE TEVA 50 mg X1 Per Day, Eve...",SERTRALINE TEVA,ACUTE KIDNEY FAILURE;PNEUMONIA,[אבחנה ללא קוד];ACUTE KIDNEY FAILURE;BENIGN ES...,12564,2703.0,DDI-Undetermined Severity - Alternative Therap...,NaN,NaN,DDI - Alert Severity 1,2022-05-20 00:04:55.582999706+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,N06AB06,0,24_33357780,18,14,"['[אבחנה ללא קוד]', 'ACUTE KIDNEY FAILURE', 'B...",2,0,0,0,1,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,5,9,0.00,adult,> 85,"CIRCADIN,SERTRALINE",0.0,0,0,0,0,0,0,0,0,0,2022-05-20,3,NaN,0,0,0,0,0,0,0,0,0,0,Non_Error_alert,Non_stopping_alert,PSYCHOANALEPTICS,OTHER,WEEKEND,0,Large hospital,new_internal,1,0,0,0,0,1,0,0,0,1,1,1,0,0,0,No_response_need,NaN,NaN
9,24,SOROKA,Surgery,Active Mode,8587847,2.022004e+09,38.0,MALE,DOCTOR,2022-01-17T10:51:39Z,NaN,NaN,NaN,NaN,Medication Order,morning,Monday,16,4,NaN,Non_alert,Naso Gastric Tube MAALOX 200mg+175mg/5mL 20 ml...,MAALOX 200mg+175mg/5mL,ABDOMINAL PAIN;DIABETES MELLITUS;EPILEPSY;GAST...,"EPILEPSY - SP;OBESITY, UNSPECIFIED;TOBACCO USE...",64359,3327.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,A02AD01,0,24_32078562,17,3,"['EPILEPSY - SP', 'OBESITY, UNSPECIFIED', 'TOB...",6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,98.30,adult,31-44,NaN,0.0,0,0,0,0,0,0,0,0,0,2022-01-17,2,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert,DRUGS FOR ACID RELATED DISORDERS,OTHER,WEEKDAY,0,Large hospital,Surgery,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,No_response_need,0.0,0.0

In [3]:
df_main_active_adult.columns.to_list()

['hospital_code',
 'hospital_name',
 'unit_category',
 'severity_level_to_stop_order',
 'medical_record',
 'admission_num',
 'age',
 'gender',
 'sector',
 'time_prescribing_order',
 'alert_drug_header',
 'module_alert_rn',
 'alert_message',
 'alert_severity',
 'order_origin',
 'shift_type',
 'day',
 'currently_hospitalized',
 'num_med_order',
 'response_reasons_other_text',
 'response_type',
 'order_details',
 'drug_name_order',
 'chronic_diagnosis',
 'hospital_diagnosis',
 'id1',
 'id2',
 'alert_rn_severity',
 'response_reasons_codes',
 'response_reasons__selected_text',
 'module_severity_rn',
 'mabat_request_time_ms',
 'mabat_response_time_ms',
 'response_time',
 'dosing_subgroup',
 'neodosing_subgroup',
 'dosing_frequency_direction',
 'dosing_single_dose_direction',
 'dosing_max_daily_dose_direction',
 'neo_dosing_frequency_direction',
 'neo_dosing_single_dose_direction',
 'neo_dosing_max_daily_dose_direction',
 'atc_count',
 'drug_atc',
 'chronic_drug_count',
 'drug_order_id',
 'medication_orders_hospitalization',
 'diagnosis_count',
 'disease_split',
 'num_of_chronic_diagnosis',
 'liver_count',
 'hepatic_count',
 'cirrhosis_count',
 'hepatitis_count',
 'portal_hypertension_count',
 'jaundice_count',
 'myocardial_count',
 'heart_failure_count',
 'peripheral_vascular _disease_count',
 'pvd_count',
 'cerebrovascular_count',
 'stroke_count',
 'cerebral_infarction_count',
 'tia_count',
 'cva_count',
 'dementia_count',
 'chronic_ pulmonary _disease_count',
 'copd_count',
 'chronic _obstructive _pulmonary _disease_count',
 'rheumatic_disease_count',
 'fibromyalgia_count',
 'gout_count',
 'arthritis_count',
 'ankylosing_spondylitis_count',
 'scleroderma_count',
 'duodenal_ulcer_count',
 'peptic_ulcer_count',
 'gastric_ulcer_count',
 'diabetes_count',
 'hemiplegia_count',
 'hemiparesis_count',
 'paraplegia_count',
 'renal_count',
 'pyelonephritis_count',
 'hemodialysis_count',
 'kidney_count',
 'ckd_count',
 'arf_count',
 'aki_count',
 'malignancy_count',
 'malignant_count',
 'carcinoma_count',
 'neoplasm_count',
 'adenocarcinoma_count',
 'leukemia_count',
 'aml_count',
 'cml_count',
 'lymphoma_count',
 'hiv_count',
 'metastatic_count',
 'metastasis_count',
 'liver_group_count',
 'pvd_group_count',
 'cerebrovascular_group_count',
 'copd_group_count',
 'gout_group_count',
 'ulcer_group_count',
 'hemiplegia_group_count',
 'renal_group_count',
 'malignancy_group_count',
 'leukemia_group_count',
 'metastatic_group_count',
 'charlson_score',
 'charlson_score_age_adj',
 'survival_rate_10y_age_adj',
 'age_group',
 'age_category',
 'drugs_in_alert_message',
 'alerts_per_order_count',
 'allergy',
 'ddi_contraindicated_severity',
 'ddi_moderate_severity',
 'ddi_severe_severity',
 'dosing',
 'technical_alerts',
 'renal_alerts',
 'neo_dosing',
 'chronic_med_count',
 'date_time_prescribe',
 'hospital_days',
 'diff_time_mabat_y',
 'dosing_duration',
 'dosing_frequency',
 'dosing_max_daily_dose',
 'dosing_message',
 'dosing_single_dose',
 'neo_dosing_duration',
 'neo_dosing_frequency',
 'neo_dosing_max_daily_dose',
 'neo_dosing_message',
 'neo_dosing_single_dose',
 'alert_type',
 'alert_status',
 'atc_group',
 'atc_group_ud',
 'prescription_day',
 'chronic_med_ud',
 'hospital_category',
 'unit_category_ud',
 'kidney_disease',
 'hepatic_disease',
 'diabetes_disease',
 'ischemic_heart_disease',
 'copd_disease',
 'cerebrovascular_disease',
 'peptic_ulcer_disease',
 'dementia_disease',
 'oncological_disease',
 'hemato_oncological_disease',
 'hypertension_disease',
 'atrial_fibrillation_disease',
 'hyperlipidemia_disease',
 'congestive_heart_failure_disease',
 'obesity_disease',
 'response_type_ud',
 'alert_type_binary',
 'alert_status_binary']

In [4]:
df_main_active_adult['chronic_diagnosis'].value_counts()

chronic_diagnosis
CHEST PAIN                                                                                               31720
FEVER                                                                                                    20108
CORONAVIRUS (COVID-19) INFECTION                                                                         13090
PNEUMONIA                                                                                                11329
Dyspnea                                                                                                  10898
                                                                                                         ...
MALIGNANT NEOPLASM OF BILIARY TRACT, PART UNSPECIF - SP                                                      1
[אבחנה ללא קוד];HYPOTHYROIDISM;PAROXYSMAL SUPRAVENTRICULAR TACHYCARDIA;WOLFF-PARKINSON-WHITE SYNDROME        1
COLOSTOMY STATUS;EXPLORATORY LAPAROTOMY                                                                      1
TRANSIENT ALTERATION OF AWARENESS                                                                            1
ANEMIA, UNSPECIFIED;Vaginal Bleeding                                                                         1
Name: count, Length: 46685, dtype: int64

In [5]:
# count_columns = [col for col in df_main_active_adult.columns if col.endswith('_count')]
# count_columns

In [6]:
df_main_active_adult.loc[df_main_active_adult['id1'] == 4969][[
        'id1',   # patient ID
         'medical_record', # patient record ID
         'hospital_name',
         'hospital_category',  # new column withr new categories for hospital_code which renamed from hospital_code we have 3 categories small, medium, large   
         'hospital_days', 
         'currently_hospitalized', # number of patients hopspitalized in the department in the moment of the prescription
         'sector',
         'order_origin',
         'drug_order_id',
         'age',  # renamed from AGE_num
         'age_category',  # renamed from Age_cat
        'prescription_day',  # new column withr new categories for day which renamed from day we have 2 categories weekend and weekday
        'unit_category',  # renamed from UnitName_cat
        'unit_category_ud',  # new column withr new categories for unit_category which renamed from UnitName_cat
        'chronic_diagnosis',  # renamed from DiagnosisInReception
        'hospital_diagnosis',  # renamed from HospDiagnosis
        'chronic_med_count',  # renamed from chronic_num_calc
        'chronic_med_ud',  # new column withr new categories for chronic_med_count which renamed from chronic_med_ud we have 3 categories 0, <5, >=5
        'alert_type',  # renamed from Alert_type
        'alert_type_binary',  # new column withr new categories for alert_type which renamed from Alert_type while 1=error alert and 0=non_alert and non_error alert
        'response_type_ud',  # new ResponseType_cat 
        'response_reasons_other_text',  # renamed from Other_Text
        'response_time',
        'diff_time_mabat_y',
        'dosing_frequency',  
        'dosing_single_dose',  
        'dosing_max_daily_dose',  
        'neo_dosing_frequency',  
        'neo_dosing_single_dose',  
        'neo_dosing_max_daily_dose',  
        'kidney_disease',   
        'hepatic_disease',
        'diabetes_disease',
        'obesity_disease',
        'hypertension_disease',
        'ischemic_heart_disease',
        'atrial_fibrillation_disease',
        'congestive_heart_failure_disease',
        'hyperlipidemia_disease',
        'cerebrovascular_disease',
        'peptic_ulcer_disease',
        'copd_disease',
        'dementia_disease',
        'oncological_disease',
        'hemato_oncological_disease',
        'atc_group',
    'atc_group_ud',  # new column withr new categories for atc_group which renamed from atc_group
    'atc_count',
    'drug_atc',
    'chronic_drug_count',
    'diabetes_count'
    
    ]]

    #TODO: add the column currently_hospitalized to the dataframe , the number of patients hopspitalized in the department in the moment of the prescription

,id1,medical_record,hospital_name,hospital_category,hospital_days,currently_hospitalized,sector,order_origin,drug_order_id,age,age_category,prescription_day,unit_category,unit_category_ud,chronic_diagnosis,hospital_diagnosis,chronic_med_count,chronic_med_ud,alert_type,alert_type_binary,response_type_ud,response_reasons_other_text,response_time,diff_time_mabat_y,dosing_frequency,dosing_single_dose,dosing_max_daily_dose,neo_dosing_frequency,neo_dosing_single_dose,neo_dosing_max_daily_dose,kidney_disease,hepatic_disease,diabetes_disease,obesity_disease,hypertension_disease,ischemic_heart_disease,atrial_fibrillation_disease,congestive_heart_failure_disease,hyperlipidemia_disease,cerebrovascular_disease,peptic_ulcer_disease,copd_disease,dementia_disease,oncological_disease,hemato_oncological_disease,atc_group,atc_group_ud,atc_count,drug_atc,chronic_drug_count,diabetes_count
48528,4969,10455613,BELINSON,Large hospital,1,22,DOCTOR,Medication Order,20_22685161,79.0,76-85,WEEKDAY,Internal-Covid19,new_internal,CORONAVIRUS (COVID-19) INFECTION,ALZHEIMER`S DISEASE;DIABETES MELLITUS;HYPERTEN...,8,0,Non_Error_alert,NaN,No_response_need,NaN,NaN,NaN,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,CORTICOSTEROIDS FOR SYSTEMIC USE,OTHER,1,H02AB02,0,1
79965,4969,10455613,BELINSON,Large hospital,1,22,DOCTOR,Chronic Meds,20_22685154_0,79.0,76-85,WEEKDAY,Internal-Covid19,new_internal,CORONAVIRUS (COVID-19) INFECTION,ALZHEIMER`S DISEASE;DIABETES MELLITUS;HYPERTEN...,8,>=5,Non_alert,0.0,No_response_need,NaN,NaN,NaN,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,DRUGS FOR CONSTIPATION,OTHER,1,A06AD11,0,1
476479,4969,10597949,SHARON,Small hospital,2,17,DOCTOR,Chronic Meds,22_22996276_0,79.0,76-85,WEEKDAY,Surgery,Surgery,CHOLELITHIASIS,NaN,7,>=5,Non_alert,0.0,No_response_need,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,ANTIEPILEPTICS,OTHER,1,N03AB02,0,0
646106,4969,10455613,BELINSON,Large hospital,1,22,DOCTOR,Chronic Meds,20_22685157_0,79.0,76-85,WEEKDAY,Internal-Covid19,new_internal,CORONAVIRUS (COVID-19) INFECTION,ALZHEIMER`S DISEASE;DIABETES MELLITUS;HYPERTEN...,8,>=5,Non_alert,0.0,No_response_need,NaN,NaN,NaN,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,DRUGS FOR ACID RELATED DISORDERS,OTHER,1,A02BC03,0,1
698751,4969,10597949,SHARON,Small hospital,2,19,DOCTOR,Protocol,22_22999654,79.0,76-85,WEEKDAY,Surgery,Surgery,CHOLELITHIASIS,NaN,0,0,Non_alert,0.0,No_response_need,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,ANALGESICS,ANALGESICS,1,N02BB02,0,0
752284,4969,10597949,SHARON,Small hospital,2,19,DOCTOR,Protocol,22_22999658,79.0,76-85,WEEKDAY,Surgery,Surgery,CHOLELITHIASIS,NaN,0,0,Non_alert,0.0,No_response_need,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,ANALGESICS,ANALGESICS,1,N02AJ13,0,0
925784,4969,10455613,BELINSON,Large hospital,1,22,DOCTOR,Chronic Meds,20_22685155_0,79.0,76-85,WEEKDAY,Internal-Covid19,new_internal,CORONAVIRUS (COVID-19) INFECTION,ALZHEIMER`S DISEASE;DIABETES MELLITUS;HYPERTEN...,8,>=5,Non_alert,0.0,No_response_need,NaN,NaN,NaN,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,ANTIEPILEPTICS,OTHER,1,N03AB02,0,1
936191,4969,10455613,BELINSON,Large hospital,1,22,DOCTOR,Chronic Meds,20_22685156_0,79.0,76-85,WEEKDAY,Internal-Covid19,new_internal,CORONAVIRUS (COVID-19) INFECTION,ALZHEIMER`S DISEASE;DIABETES MELLITUS;HYPERTEN...,8,>=5,Non_alert,0.0,No_response_need,NaN,NaN,NaN,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,DRUGS USED IN DIABETES,DRUGS USED IN DIABETES,1,A10BA02,0,1
1056741,4969,10597949,SHARON,Small hospital,2,17,DOCTOR,Chronic Meds,22_22996281_0,79.0,76-85,WEEKDAY,Surgery,Surgery,CHOLELITHIASIS,NaN,7,>=5,Non_alert,0.0,No_response_need,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DRUGS FOR CONSTIPATION,OTHER,1,A06AD15,0,0
1066875,4969,10597949,SHARON,Small hospital,2,17,DOCTOR,Chronic Meds,22_22996279_0,79.0,76-85,WEEKDAY,Surgery,Surgery,CHOLELITHIASIS,NaN,7,>=5,Non_alert,0.0,No_response_need,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,LIPID MODIFYING AGENTS,CARDIOVASCULAR DRUGS,1,C10AA05,0,0
1181247,4969,10597949,SHARON,Small hospital,2,17,DOCTOR,Chronic Meds,22_22996275_0,79.0,76-85,WEEKDAY,Surgery,Surgery,CHOLELITHIASIS,NaN,7,>=5,Non_Error_alert,NaN,No_response_need,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DRUGS FOR ACID RELATED DISORDERS,OTHER,1,A02BC03,0,0
1468970,4969,10597949,SHARON,Small hospital,2,17,DOCTOR,Chronic Meds,22_22996280_0,79.0,76-85,WEEKDAY,Surgery,Surgery,CHOLELITHIASIS,NaN,7,>=5,Non_alert,0.0,No_response_need,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,AGENTS ACTING ON THE RENIN-ANGIOTENSIN SYSTEM,CARDIOVASCULAR DRUGS,1,C09CA01,0,0
1478141,4969,10597949,SHARON,Small hospital,2,17,DOCTOR,Chronic Meds,22_22996277_0,79.0,76-85,WEEKDAY,Surgery,Surgery,CHOLELITHIASIS,NaN,7,>=5,Non_alert,0.0,No_response_need,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DRUGS USED IN DIABETES,DRUGS USED IN DIABETES,1,A10BA02,0,0
1511518,4969,10455613,BELINSON,Large hospital,1,22,DOCTOR,Medication Order,20_22685171,79.0,76-85,WEEKDAY,Internal-Covid19,new_internal,CORONAVIRUS (COVID-19) INFECTION,ALZHEIMER`S DISEASE;DIABETES MELLITUS;HYPERTEN...,8,0,Non_alert,0.0,No_response_need,NaN,NaN,NaN,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,ANTITHROMBOTIC AGENTS,ANTITHROMBOTIC AGENTS,1,B01AB05,0,1
1866430,4969,10455613,BELINSON,Large hospital,1,22,DOCTOR,Chronic Meds,20_22685153_0,79.0,76-85,WEEKDAY,Internal-Covid19,new_internal,CORONAVIRUS (COVID-19) INFECTION,ALZHEIMER`S DISEASE;DIABETES MELLITUS;HYPERTEN...,8,>=5,Non_Error_alert,NaN,No_response_need,NaN,NaN,NaN,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,DRUGS FOR ACID RELATED DISORDERS,OTHER,1,A02BC03,0,1
1893217,4969,10455613,BELINSON,Large hospital,1,22,DOCTOR,Chronic Meds,20_22685159_0,79.0,76-85,WEEKDAY,Internal-Covid19,new_internal,CORONAVIRUS (COVID-19) INFECTION,ALZHEIMER`S DISEASE;DIABETES MELLITUS;HYPERTEN...,8,>=5,Non_alert,0.0,No_response_need,NaN,NaN,NaN,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,AGENTS ACTING ON THE RENIN-ANGIOTENSIN SYSTEM,CARDIOVASCULAR DRUGS,1,C09CA01,0,1
1907519,4969,10455613,BELINSON,Large hospital,1,22,DOCTOR,Chronic Meds,20_22685158_0,79.0,76-85,WEEKDAY,Internal-Covid19,new_internal,CORONAVIRUS (COVID-19) INFECTION,ALZHEIMER`S DISEASE;DIABETES MELLITUS;HYPERTEN...,8,>=5,Non_alert,0.0,No_response_need,NaN,NaN,NaN,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,LIPID MODIFYING AGENTS,CARDIOVASCULAR DRUGS,1,C10AA05,0,1
2206039,4969,10597949,SHARON,Small hospital,2,17,DOCTOR,Chronic Meds,22_22996278_0,79.0,76-85,WEEKDAY,Surgery,Surgery,CHOLELITHIASIS,NaN,7,>=5,Non_alert,0.0,No_response_need,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DRUGS FOR ACID RELATED DISORDERS,OTHER,1,A02BC03,0,0
2339169,4969,10597949,SHARON,Small hospital,2,19,DOCTOR,Protocol,22_22999663,79.0,76-85,WEEKDAY,Surgery,Surgery,CHOLELITHIASIS,NaN,0,0,Non_alert,0.0,No_response_need,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DRUGS USED IN DIABETES,DRUGS USED IN DIABETES,1,A10AB06,0,0
2377424,4969,10455613,BELINSON,Large hospital,1,22,DOCTOR,Chronic Meds,20_22685160_0,79.0,76-85,WEEKDAY,Internal-Covid19,new_internal,CORONAVIRUS (COVID-19) INFECTION,ALZHEIMER`S DISEASE;DIABETES MELLITUS;HYPERTEN...,8,>=5,Non_alert,0.0,No_response_need,NaN,NaN,NaN,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,DRUGS FOR CONSTIPATION,OTHER,1,A06AD15,0,1

## Part 2: Alert analysis

In [7]:
#alert type & alert type binary counts (NIR WHY IT DOSENT WORK FOR ALERT TYPE??)
alert_counts = df_main_active_adult['alert_type'].value_counts()
alert_counts_binary = df_main_active_adult['alert_type_binary'].value_counts()

#alert type counts 
alert_counts = df_main_active_adult['alert_type'].value_counts()
alert_df = alert_counts.to_frame().reset_index()
alert_df.columns = ['alert_type', 'count']
alert_df['fraction'] = alert_df['count'] / alert_df['count'].sum()
alert_df
#tools.display_dataframe_to_user(name="Alert Type Distribution", dataframe=alert_df)

# Check data types
print("alert_type dtype:", df_main_active_adult['alert_type'].dtype)
print("alert_type_binary dtype:", df_main_active_adult['alert_type_binary'].dtype)
print("\nalert_type unique values:", df_main_active_adult['alert_type'].unique())
print("alert_type_binary unique values:", df_main_active_adult['alert_type_binary'].unique())

#alert type binary counts 
alert_counts_binary = df_main_active_adult['alert_type_binary'].value_counts()
alert_df_binary = alert_counts_binary.to_frame().reset_index()
alert_df_binary.columns = ['alert_type_binary', 'count']
alert_df_binary['fraction'] = alert_df_binary['count'] / alert_df_binary['count'].sum()
alert_df_binary

alert_type dtype: object
alert_type_binary dtype: float64

alert_type unique values: ['Non_alert' 'Non_Error_alert' 'Error_Alert']
alert_type_binary unique values: [ 0. nan  1.]

   alert_type_binary    count  fraction
0                0.0  2061122   0.96886
1                1.0    66246   0.03114

## Fix for alert_type in TableOne

**Issue:** `alert_type` (string categorical) may cause errors in TableOne when `pval=True` because:
- String categorical variables with multiple categories can cause issues with statistical tests
- `alert_type_binary` (numeric 0/1) works better with TableOne's p-value calculations

**Solutions:**
1. Use `alert_type_binary` instead (recommended for statistical tests)
2. Convert `alert_type` to categorical type before using in TableOne
3. Set `pval=False` if you need `alert_type` but don't need p-values

In [8]:
#convert alert_type to categorical type before using in TableOne
df_main_active_adult['alert_type'] = df_main_active_adult['alert_type'].astype('category')

# Optional: If you need to use alert_type in TableOne, convert it to categorical type first
# Uncomment the line below before running TableOne:

## Table summary  order_id by Alert Type (Active mode)

In [9]:
categorical_vars =  [
    "hospital_name",
    "hospital_category",
    "unit_category",
    "unit_category_ud",
    "age_category",
    "gender",
    "shift_type",
    "day",
    "prescription_day",
    "chronic_med_ud",
    "sector",
    "order_origin",
    "atc_group_ud", 
    "alert_status",
    "alert_rn_severity",
    #"allergy",  alerts distribution per order dosent , not all included in the flat data 
    #"ddi_contraindicated_severity",alerts distribution per order dosent , not all included in the flat data
    #"ddi_moderate_severity",alerts distribution per order dosent , not all included in the flat data
    #"ddi_severe_severity",alerts distribution per order dosent , not all included in the flat data
    #"dosing",
    #"renal_alerts",alerts distribution per order dosent , not all included in the flat data
    #"dosing_message",alerts distribution per order dosent , not all included in the flat data
    #"technical_alerts",alerts distribution per order dosent , not all included in the flat data
    "response_type_ud", 
]


continuous_vars =[ 'age',
                   'survival_rate_10y_age_adj',
                   'charlson_score_age_adj',
                   'diagnosis_count',
                   'medication_orders_hospitalization',
                   'chronic_med_count',
                   'response_time',
                   'hospital_days',
                   'currently_hospitalized', # number of patients hopspitalized in the department in the moment of the prescription
                   ]


table_alert_type = TableOne(
   df_main_active_adult, # use always for other groupby like alert_type / alert_status and binary
   #df_filtered_reponse_type, # use only for groupby response_type (for now not good enough)
   categorical=categorical_vars,
   groupby="alert_type",
   continuous=continuous_vars,
   pval=True,   # Add p-values
   missing=False  # don't Show missing values
)

In [10]:
#print(table_alert_type.tabulate(tablefmt="pipe"))
table_alert_type.head(105)

                                                                                                Grouped by alert_type  \
                                                                                                              Overall
n                                                                                                             2477205
hospital_name, n (%)                         BELINSON                                                    223374 (9.0)
                                             CARMEL                                                     288906 (11.7)
                                             EMEK                                                       282077 (11.4)
                                             KAPLAN                                                     394886 (15.9)
                                             MEIR                                                       416000 (16.8)
                                             SHARON                                                      157019 (6.3)
                                             SOROKA                                                     687818 (27.8)
                                             YOSEFTAL                                                     27125 (1.1)
unit_category, n (%)                         Cardiology                                                   98873 (4.0)
                                             Emergency                                                    79199 (3.2)
                                             Geriatric                                                    30264 (1.2)
                                             Gynecology                                                  105987 (4.3)
                                             Hematology                                                   21252 (0.9)
                                             Internal                                                  1304198 (52.6)
                                             Internal-Covid19                                             72221 (2.9)
                                             Nephrology                                                   19481 (0.8)
                                             Oncology                                                      2565 (0.1)
                                             Surgery                                                    743165 (30.0)
age, mean (SD)                                                                                            67.1 (18.7)
gender, n (%)                                FEMALE                                                    1204569 (48.6)
                                             MALE                                                      1272636 (51.4)
sector, n (%)                                DOCTOR                                                    2326403 (93.9)
                                             NURSE                                                       150802 (6.1)
order_origin, n (%)                          Chronic Meds                                               691996 (27.9)
                                             Medication Order                                          1364314 (55.1)
                                             Protocol                                                   420895 (17.0)
shift_type, n (%)                            afternoon                                                  946709 (38.2)
                                             morning                                                   1047805 (42.3)
                                             night                                                      482691 (19.5)
day, n (%)                                   Friday                                                     292257 (11.8)
                                             Monday                                                     398237 (16.1)
                                             Saturday                                                   257208 (10.4)
                                             Sunday                                                     383455 (15.5)
                                             Thursday                                                   360389 (14.5)
                                             Tuesday                                                    399022 (16.1)
                                             Wednesday                                                  386637 (15.6)
currently_hospitalized, mean (SD)                                                                         23.2 (11.8)
alert_rn_severity, n (%)                     DAM                                                           8688 (0.4)
                                             DDI-Contraindicated Drug Combination                          2790 (0.1)
                                             DDI-Moderate Interaction                                   269275 (10.9)
                                             DDI-Severe Interaction                                       50998 (2.1)
                                             DDI-Undetermined Severity - Alternative Therapy...             450 (0.0)
                                             DRC                                                          48468 (2.0)
                                             None                                                      2061122 (83.2)
                                             Renal alerts                                                  6300 (0.3)
                                             Technical alert                                              29114 (1.2)
response_time, mean (SD)                                                                            10081.1 (29218.1)
medication_orders_hospitalization, mean (SD)                                                              20.9 (22.2)
diagnosis_count, mean (SD)                                                                                  3.4 (3.8)
charlson_score_age_adj, mean (SD)                                                                           3.9 (2.8)
survival_rate_10y_age_adj, mean (SD)                                                                      52.3 (38.9)
age_category, n (%)                          19-30                                                       157807 (6.4)
                                             31-44                                                       201070 (8.1)
                                             45-55                                                       222060 (9.0)
                                             56-64                                                      302364 (12.2)
                                             65-75                                                      644288 (26.0)
                                             76-85                                                      584451 (23.6)
                                             > 85                                                       365165 (14.7)
chronic_med_count, mean (SD)                                                                                3.5 (4.2)
hospital_days, mean (SD)                                                                                    5.9 (9.2)
alert_status, n (%)                          Non_alert                                                 2061122 (83.2)
                                             Non_stopping_alert                                         320723 (12.9)
                                             Stopping_alert                                               95360 (3.8)
atc_group_ud, n (%)                          ANALGESICS                                                 424017 (17.1)
                                             ANTIBACTERIALS FOR SYSTEMIC USE                             166250 (6.7)
                                             ANTITHROMBOTIC AGENTS                                       206111 (8.3)
                                             CARDIOVASCULAR DRUGS                                       462775 (18.7)
                                             DRUGS USED IN DIABETES                                      156585 (6.3)
                                             OTHER                                                     1061467 (42.8)
prescription_day, n (%)                      WEEKDAY                                                   1927740 (77.8)
                                             WEEKEND                                                    549465 (22.2)
chronic_med_ud, n (%)                        0                                                         1785209 (72.1)
                                             <5                                                          128232 (5.2)
                                             >=5                                                        563764 (22.8)
hospital_category, n (%)                     Large hospital                                             911192 (36.8)
                                             Medium hospital                                           1092963 (44.1)
                                             Small hospital                                             473050 (19.1)
unit_category_ud, n (%)                      Emergency                                                    79199 (3.2)
                                             OTHER                                                      278422 (11.2)
                                             Surgery                                                    743165 (30.0)
                                             new_internal                                              1376419 (55.6)
response_type_ud, n (%)                      Change                                                       17856 (0.7)
                                             Ignore                                                       78610 (3.2)
                                             No_response_need                                          2380739 (96.1)

                                                                                                                    \
                                                                                                       Error_Alert
n                                                                                                            66246
hospital_name, n (%)                         BELINSON                                                  6725 (10.2)
                                             CARMEL                                                    6985 (10.5)
                                             EMEK                                                      9556 (14.4)
                                             KAPLAN                                                    9524 (14.4)
                                             MEIR                                                      7804 (11.8)
                                             SHARON                                                     5386 (8.1)
                                             SOROKA                                                   19616 (29.6)
                                             YOSEFTAL                                                    650 (1.0)
unit_category, n (%)                         Cardiology                                                 1977 (3.0)
                                             Emergency                                                  1140 (1.7)
                                             Geriatric                                                   674 (1.0)
                                             Gynecology                                                 2364 (3.6)
                                             Hematology                                                  396 (0.6)
                                             Internal                                                 35176 (53.1)
                                             Internal-Covid19                                           2123 (3.2)
                                             Nephrology                                                  810 (1.2)
                                             Oncology                                                     80 (0.1)
                                             Surgery                                                  21506 (32.5)
age, mean (SD)                                                                                         67.7 (18.9)
gender, n (%)                                FEMALE                                                   34261 (51.7)
                                             MALE                                                     31985 (48.3)
sector, n (%)                                DOCTOR                                                   62904 (95.0)
                                             NURSE                                                      3342 (5.0)
order_origin, n (%)                          Chronic Meds                                             17625 (26.6)
                                             Medication Order                                         40080 (60.5)
                                             Protocol                                                  8541 (12.9)
shift_type, n (%)                            afternoon                                                26203 (39.6)
                                             morning                                                  27053 (40.8)
                                             night                                                    12990 (19.6)
day, n (%)                                   Friday                                                    7991 (12.1)
                                             Monday                                                   10621 (16.0)
                                             Saturday                                                  6865 (10.4)
                                             Sunday                                                   10360 (15.6)
                                             Thursday                                                  9770 (14.7)
                                             Tuesday                                                  10576 (16.0)
                                             Wednesday                                                10063 (15.2)
currently_hospitalized, mean (SD)                                                                      23.8 (11.5)
alert_rn_severity, n (%)                     DAM                                                       8688 (13.1)
                                             DDI-Contraindicated Drug Combination                       2790 (4.2)
                                             DDI-Moderate Interaction                                      0 (0.0)
                                             DDI-Severe Interaction                                        0 (0.0)
                                             DDI-Undetermined Severity - Alternative Therapy...            0 (0.0)
                                             DRC                                                      48468 (73.2)
                                             None                                                          0 (0.0)
                                             Renal alerts                                               6300 (9.5)
                                             Technical alert                                               0 (0.0)
response_time, mean (SD)                                                                         10514.2 (33541.0)
medication_orders_hospitalization, mean (SD)                                                           22.9 (22.1)
diagnosis_count, mean (SD)                                                                               3.7 (3.9)
charlson_score_age_adj, mean (SD)                                                                        4.1 (2.9)
survival_rate_10y_age_adj, mean (SD)                                                                   49.5 (39.3)
age_category, n (%)                          19-30                                                      4199 (6.3)
                                             31-44                                                      5252 (7.9)
                                             45-55                                                      5530 (8.3)
                                             56-64                                                     7837 (11.8)
                                             65-75                                                    16516 (24.9)
                                             76-85                                                    16160 (24.4)
                                             > 85                                                     10752 (16.2)
chronic_med_count, mean (SD)                                                                             3.6 (4.3)
hospital_days, mean (SD)                                                                                 6.2 (9.1)
alert_status, n (%)                          Non_alert                                                     0 (0.0)
                                             Non_stopping_alert                                            0 (0.0)
                                             Stopping_alert                                          66246 (100.0)
atc_group_ud, n (%)                          ANALGESICS                                               14633 (22.1)
                                             ANTIBACTERIALS FOR SYSTEMIC USE                           7737 (11.7)
                                             ANTITHROMBOTIC AGENTS                                      3875 (5.8)
                                             CARDIOVASCULAR DRUGS                                     11414 (17.2)
                                             DRUGS USED IN DIABETES                                     4474 (6.8)
                                             OTHER                                                    24113 (36.4)
prescription_day, n (%)                      WEEKDAY                                                  51390 (77.6)
                                             WEEKEND                                                  14856 (22.4)
chronic_med_ud, n (%)                        0                                                        48621 (73.4)
                                             <5                                                         3508 (5.3)
                                             >=5                                                      14117 (21.3)
hospital_category, n (%)                     Large hospital                                           26341 (39.8)
                                             Medium hospital                                          26884 (40.6)
                                             Small hospital                                           13021 (19.7)
unit_category_ud, n (%)                      Emergency                                                  1140 (1.7)
                                             OTHER                                                      6301 (9.5)
                                             Surgery                                                  21506 (32.5)
                                             new_internal                                             37299 (56.3)

## Table summary filtered order_id by Alert Type (Active mode)

In [23]:
# Table summary filtered order_id by Alert Type (Active mode)
# 1. Keep the full table
# 2. Remove rows with only value "0" (category value = 0) 
# 3. Keep chronic_med_ud rows with value "0"
# 4. Keep the "n" row (count row)

# Get the table as a DataFrame
table_df = table_alert_type.tableone.copy()

# Handle MultiIndex structure (TableOne uses MultiIndex with variable name and category value)
if isinstance(table_df.index, pd.MultiIndex):
    # Get variable names (first level) and category values (second level)
    var_names = table_df.index.get_level_values(0)
    cat_values = table_df.index.get_level_values(1) if table_df.index.nlevels > 1 else None
    
    # Create mask for filtering
    if cat_values is not None:
        # Convert category values to string for comparison
        cat_values_str = cat_values.astype(str).str.strip()
        
        # Conditions:
        # 1. Keep rows where category value is NOT "0" or "0.0"
        # 2. Keep rows where variable is "chronic_med_ud" (even if value is "0")
        # 3. Keep rows where variable is "n" (the count row)
        is_not_zero = ~cat_values_str.isin(['0', '0.0'])
        is_chronic_med_ud = var_names.str.contains('chronic_med_ud', case=False, na=False, regex=False)
        is_n_row = var_names.str.strip().str.lower() == 'n'
        
        # Combine conditions: keep if (not zero) OR (chronic_med_ud) OR (n row)
        keep_mask = is_not_zero | is_chronic_med_ud | is_n_row
        
        filtered_table = table_df[keep_mask]
    else:
        # If no category values, keep all rows (including "n" row)
        filtered_table = table_df
else:
    # For non-MultiIndex, keep the full table
    filtered_table = table_df

# Drop the "missing" column if it exists
filtered_table = filtered_table.drop(columns=['missing'], errors='ignore')

# Display the filtered table
filtered_table

                                                                                                Grouped by alert_type  \
                                                                                                              Overall
n                                                                                                             2477205
hospital_name, n (%)                         BELINSON                                                    223374 (9.0)
                                             CARMEL                                                     288906 (11.7)
                                             EMEK                                                       282077 (11.4)
                                             KAPLAN                                                     394886 (15.9)
                                             MEIR                                                       416000 (16.8)
                                             SHARON                                                      157019 (6.3)
                                             SOROKA                                                     687818 (27.8)
                                             YOSEFTAL                                                     27125 (1.1)
unit_category, n (%)                         Cardiology                                                   98873 (4.0)
                                             Emergency                                                    79199 (3.2)
                                             Geriatric                                                    30264 (1.2)
                                             Gynecology                                                  105987 (4.3)
                                             Hematology                                                   21252 (0.9)
                                             Internal                                                  1304198 (52.6)
                                             Internal-Covid19                                             72221 (2.9)
                                             Nephrology                                                   19481 (0.8)
                                             Oncology                                                      2565 (0.1)
                                             Surgery                                                    743165 (30.0)
age, mean (SD)                                                                                            67.1 (18.7)
gender, n (%)                                FEMALE                                                    1204569 (48.6)
                                             MALE                                                      1272636 (51.4)
sector, n (%)                                DOCTOR                                                    2326403 (93.9)
                                             NURSE                                                       150802 (6.1)
order_origin, n (%)                          Chronic Meds                                               691996 (27.9)
                                             Medication Order                                          1364314 (55.1)
                                             Protocol                                                   420895 (17.0)
shift_type, n (%)                            afternoon                                                  946709 (38.2)
                                             morning                                                   1047805 (42.3)
                                             night                                                      482691 (19.5)
day, n (%)                                   Friday                                                     292257 (11.8)
                                             Monday                                                     398237 (16.1)
                                             Saturday                                                   257208 (10.4)
                                             Sunday                                                     383455 (15.5)
                                             Thursday                                                   360389 (14.5)
                                             Tuesday                                                    399022 (16.1)
                                             Wednesday                                                  386637 (15.6)
currently_hospitalized, mean (SD)                                                                         23.2 (11.8)
alert_rn_severity, n (%)                     DAM                                                           8688 (0.4)
                                             DDI-Contraindicated Drug Combination                          2790 (0.1)
                                             DDI-Moderate Interaction                                   269275 (10.9)
                                             DDI-Severe Interaction                                       50998 (2.1)
                                             DDI-Undetermined Severity - Alternative Therapy...             450 (0.0)
                                             DRC                                                          48468 (2.0)
                                             None                                                      2061122 (83.2)
                                             Renal alerts                                                  6300 (0.3)
                                             Technical alert                                              29114 (1.2)
response_time, mean (SD)                                                                            10081.1 (29218.1)
medication_orders_hospitalization, mean (SD)                                                              20.9 (22.2)
diagnosis_count, mean (SD)                                                                                  3.4 (3.8)
charlson_score_age_adj, mean (SD)                                                                           3.9 (2.8)
survival_rate_10y_age_adj, mean (SD)                                                                      52.3 (38.9)
age_category, n (%)                          19-30                                                       157807 (6.4)
                                             31-44                                                       201070 (8.1)
                                             45-55                                                       222060 (9.0)
                                             56-64                                                      302364 (12.2)
                                             65-75                                                      644288 (26.0)
                                             76-85                                                      584451 (23.6)
                                             > 85                                                       365165 (14.7)
chronic_med_count, mean (SD)                                                                                2.7 (5.3)
hospital_days, mean (SD)                                                                                    5.9 (9.2)
alert_status, n (%)                          Non_alert                                                 2061122 (83.2)
                                             Non_stopping_alert                                         320723 (12.9)
                                             Stopping_alert                                               95360 (3.8)
atc_group_ud, n (%)                          ANALGESICS                                                 424017 (17.1)
                                             ANTIBACTERIALS FOR SYSTEMIC USE                             166250 (6.7)
                                             ANTITHROMBOTIC AGENTS                                       206111 (8.3)
                                             CARDIOVASCULAR DRUGS                                       462775 (18.7)
                                             DRUGS USED IN DIABETES                                      156585 (6.3)
                                             OTHER                                                     1061467 (42.8)
prescription_day, n (%)                      WEEKDAY                                                   1927740 (77.8)
                                             WEEKEND                                                    549465 (22.2)
chronic_med_ud, n (%)                        0                                                         1785209 (72.1)
                                             <5                                                          100914 (4.1)
                                             >=5                                                        591082 (23.9)
hospital_category, n (%)                     Large hospital                                             911192 (36.8)
                                             Medium hospital                                           1092963 (44.1)
                                             Small hospital                                             473050 (19.1)
unit_category_ud, n (%)                      Emergency                                                    79199 (3.2)
                                             OTHER                                                      278422 (11.2)
                                             Surgery                                                    743165 (30.0)
                                             new_internal                                              1376419 (55.6)
response_type_ud, n (%)                      Change                                                       17856 (0.7)
                                             Ignore                                                       78610 (3.2)
                                             No_response_need                                          2380739 (96.1)

                                                                                                                    \
                                                                                                       Error_Alert
n                                                                                                            66246
hospital_name, n (%)                         BELINSON                                                  6725 (10.2)
                                             CARMEL                                                    6985 (10.5)
                                             EMEK                                                      9556 (14.4)
                                             KAPLAN                                                    9524 (14.4)
                                             MEIR                                                      7804 (11.8)
                                             SHARON                                                     5386 (8.1)
                                             SOROKA                                                   19616 (29.6)
                                             YOSEFTAL                                                    650 (1.0)
unit_category, n (%)                         Cardiology                                                 1977 (3.0)
                                             Emergency                                                  1140 (1.7)
                                             Geriatric                                                   674 (1.0)
                                             Gynecology                                                 2364 (3.6)
                                             Hematology                                                  396 (0.6)
                                             Internal                                                 35176 (53.1)
                                             Internal-Covid19                                           2123 (3.2)
                                             Nephrology                                                  810 (1.2)
                                             Oncology                                                     80 (0.1)
                                             Surgery                                                  21506 (32.5)
age, mean (SD)                                                                                         67.7 (18.9)
gender, n (%)                                FEMALE                                                   34261 (51.7)
                                             MALE                                                     31985 (48.3)
sector, n (%)                                DOCTOR                                                   62904 (95.0)
                                             NURSE                                                      3342 (5.0)
order_origin, n (%)                          Chronic Meds                                             17625 (26.6)
                                             Medication Order                                         40080 (60.5)
                                             Protocol                                                  8541 (12.9)
shift_type, n (%)                            afternoon                                                26203 (39.6)
                                             morning                                                  27053 (40.8)
                                             night                                                    12990 (19.6)
day, n (%)                                   Friday                                                    7991 (12.1)
                                             Monday                                                   10621 (16.0)
                                             Saturday                                                  6865 (10.4)
                                             Sunday                                                   10360 (15.6)
                                             Thursday                                                  9770 (14.7)
                                             Tuesday                                                  10576 (16.0)
                                             Wednesday                                                10063 (15.2)
currently_hospitalized, mean (SD)                                                                      23.8 (11.5)
alert_rn_severity, n (%)                     DAM                                                       8688 (13.1)
                                             DDI-Contraindicated Drug Combination                       2790 (4.2)
                                             DDI-Moderate Interaction                                      0 (0.0)
                                             DDI-Severe Interaction                                        0 (0.0)
                                             DDI-Undetermined Severity - Alternative Therapy...            0 (0.0)
                                             DRC                                                      48468 (73.2)
                                             None                                                          0 (0.0)
                                             Renal alerts                                               6300 (9.5)
                                             Technical alert                                               0 (0.0)
response_time, mean (SD)                                                                         10514.2 (33541.0)
medication_orders_hospitalization, mean (SD)                                                           22.9 (22.1)
diagnosis_count, mean (SD)                                                                               3.7 (3.9)
charlson_score_age_adj, mean (SD)                                                                        4.1 (2.9)
survival_rate_10y_age_adj, mean (SD)                                                                   49.5 (39.3)
age_category, n (%)                          19-30                                                      4199 (6.3)
                                             31-44                                                      5252 (7.9)
                                             45-55                                                      5530 (8.3)
                                             56-64                                                     7837 (11.8)
                                             65-75                                                    16516 (24.9)
                                             76-85                                                    16160 (24.4)
                                             > 85                                                     10752 (16.2)
chronic_med_count, mean (SD)                                                                             2.9 (5.8)
hospital_days, mean (SD)                                                                                 6.2 (9.1)
alert_status, n (%)                          Non_alert                                                     0 (0.0)
                                             Non_stopping_alert                                            0 (0.0)
                                             Stopping_alert                                          66246 (100.0)
atc_group_ud, n (%)                          ANALGESICS                                               14633 (22.1)
                                             ANTIBACTERIALS FOR SYSTEMIC USE                           7737 (11.7)
                                             ANTITHROMBOTIC AGENTS                                      3875 (5.8)
                                             CARDIOVASCULAR DRUGS                                     11414 (17.2)
                                             DRUGS USED IN DIABETES                                     4474 (6.8)
                                             OTHER                                                    24113 (36.4)
prescription_day, n (%)                      WEEKDAY                                                  51390 (77.6)
                                             WEEKEND                                                  14856 (22.4)
chronic_med_ud, n (%)                        0                                                        48621 (73.4)
                                             <5                                                         2330 (3.5)
                                             >=5                                                      15295 (23.1)
hospital_category, n (%)                     Large hospital                                           26341 (39.8)
                                             Medium hospital                                          26884 (40.6)
                                             Small hospital                                           13021 (19.7)
unit_category_ud, n (%)                      Emergency                                                  1140 (1.7)
                                             OTHER                                                      6301 (9.5)
                                             Surgery                                                  21506 (32.5)
                                             new_internal                                             37299 (56.3)

## Table summary  order_id by ATC_GROUP (Active mode)

In [11]:
table_atc_group = TableOne(
  df_main_active_adult,
  categorical=categorical_vars,
  #groupby="atc_group",
  groupby="atc_group_ud",
  continuous=continuous_vars,
  pval=True,  # Add p-values
  missing=False  # don't Show missing values
 )

# Table summary filtered order_id by ATC_GROUP (Active mode)
# 1. Keep the full table
# 2. Remove rows with only value "0" (category value = 0) 
# 3. Keep chronic_med_ud rows with value "0"
# 4. Keep the "n" row (count row)

# Get the table as a DataFrame
table_df = table_atc_group.tableone.copy()

# Handle MultiIndex structure (TableOne uses MultiIndex with variable name and category value)
if isinstance(table_df.index, pd.MultiIndex):
    # Get variable names (first level) and category values (second level)
    var_names = table_df.index.get_level_values(0)
    cat_values = table_df.index.get_level_values(1) if table_df.index.nlevels > 1 else None
    
    # Create mask for filtering
    if cat_values is not None:
        # Convert category values to string for comparison
        cat_values_str = cat_values.astype(str).str.strip()
        
        # Conditions:
        # 1. Keep rows where category value is NOT "0" or "0.0"
        # 2. Keep rows where variable is "chronic_med_ud" (even if value is "0")
        # 3. Keep rows where variable is "n" (the count row)
        is_not_zero = ~cat_values_str.isin(['0', '0.0'])
        is_chronic_med_ud = var_names.str.contains('chronic_med_ud', case=False, na=False, regex=False)
        is_n_row = var_names.str.strip().str.lower() == 'n'
        
        # Combine conditions: keep if (not zero) OR (chronic_med_ud) OR (n row)
        keep_mask = is_not_zero | is_chronic_med_ud | is_n_row
        
        filtered_atc_table = table_df[keep_mask]
    else:
        # If no category values, keep all rows (including "n" row)
        filtered_atc_table = table_df
else:
    # For non-MultiIndex, keep the full table
    filtered_atc_table = table_df

# Drop the "missing" column if it exists
filtered_atc_table = filtered_atc_table.drop(columns=['missing'], errors='ignore')

# Display the filtered table
display(filtered_atc_table)

                                                                                                Grouped by atc_group_ud  \
                                                                                                                Overall
n                                                                                                               2477205
hospital_name, n (%)                         BELINSON                                                      223374 (9.0)
                                             CARMEL                                                       288906 (11.7)
                                             EMEK                                                         282077 (11.4)
                                             KAPLAN                                                       394886 (15.9)
                                             MEIR                                                         416000 (16.8)
                                             SHARON                                                        157019 (6.3)
                                             SOROKA                                                       687818 (27.8)
                                             YOSEFTAL                                                       27125 (1.1)
unit_category, n (%)                         Cardiology                                                     98873 (4.0)
                                             Emergency                                                      79199 (3.2)
                                             Geriatric                                                      30264 (1.2)
                                             Gynecology                                                    105987 (4.3)
                                             Hematology                                                     21252 (0.9)
                                             Internal                                                    1304198 (52.6)
                                             Internal-Covid19                                               72221 (2.9)
                                             Nephrology                                                     19481 (0.8)
                                             Oncology                                                        2565 (0.1)
                                             Surgery                                                      743165 (30.0)
age, mean (SD)                                                                                              67.1 (18.7)
gender, n (%)                                FEMALE                                                      1204569 (48.6)
                                             MALE                                                        1272636 (51.4)
sector, n (%)                                DOCTOR                                                      2326403 (93.9)
                                             NURSE                                                         150802 (6.1)
order_origin, n (%)                          Chronic Meds                                                 691996 (27.9)
                                             Medication Order                                            1364314 (55.1)
                                             Protocol                                                     420895 (17.0)
shift_type, n (%)                            afternoon                                                    946709 (38.2)
                                             morning                                                     1047805 (42.3)
                                             night                                                        482691 (19.5)
day, n (%)                                   Friday                                                       292257 (11.8)
                                             Monday                                                       398237 (16.1)
                                             Saturday                                                     257208 (10.4)
                                             Sunday                                                       383455 (15.5)
                                             Thursday                                                     360389 (14.5)
                                             Tuesday                                                      399022 (16.1)
                                             Wednesday                                                    386637 (15.6)
currently_hospitalized, mean (SD)                                                                           23.2 (11.8)
alert_rn_severity, n (%)                     DAM                                                             8688 (0.4)
                                             DDI-Contraindicated Drug Combination                            2790 (0.1)
                                             DDI-Moderate Interaction                                     269275 (10.9)
                                             DDI-Severe Interaction                                         50998 (2.1)
                                             DDI-Undetermined Severity - Alternative Therapy...               450 (0.0)
                                             DRC                                                            48468 (2.0)
                                             None                                                        2061122 (83.2)
                                             Renal alerts                                                    6300 (0.3)
                                             Technical alert                                                29114 (1.2)
response_time, mean (SD)                                                                              10081.1 (29218.1)
medication_orders_hospitalization, mean (SD)                                                                20.9 (22.2)
diagnosis_count, mean (SD)                                                                                    3.4 (3.8)
charlson_score_age_adj, mean (SD)                                                                             3.9 (2.8)
survival_rate_10y_age_adj, mean (SD)                                                                        52.3 (38.9)
age_category, n (%)                          19-30                                                         157807 (6.4)
                                             31-44                                                         201070 (8.1)
                                             45-55                                                         222060 (9.0)
                                             56-64                                                        302364 (12.2)
                                             65-75                                                        644288 (26.0)
                                             76-85                                                        584451 (23.6)
                                             > 85                                                         365165 (14.7)
chronic_med_count, mean (SD)                                                                                  3.5 (4.2)
hospital_days, mean (SD)                                                                                      5.9 (9.2)
alert_status, n (%)                          Non_alert                                                   2061122 (83.2)
                                             Non_stopping_alert                                           320723 (12.9)
                                             Stopping_alert                                                 95360 (3.8)
atc_group_ud, n (%)                          ANALGESICS                                                   424017 (17.1)
                                             ANTIBACTERIALS FOR SYSTEMIC USE                               166250 (6.7)
                                             ANTITHROMBOTIC AGENTS                                         206111 (8.3)
                                             CARDIOVASCULAR DRUGS                                         462775 (18.7)
                                             DRUGS USED IN DIABETES                                        156585 (6.3)
                                             OTHER                                                       1061467 (42.8)
prescription_day, n (%)                      WEEKDAY                                                     1927740 (77.8)
                                             WEEKEND                                                      549465 (22.2)
chronic_med_ud, n (%)                        0                                                           1785209 (72.1)
                                             <5                                                            128232 (5.2)
                                             >=5                                                          563764 (22.8)
hospital_category, n (%)                     Large hospital                                               911192 (36.8)
                                             Medium hospital                                             1092963 (44.1)
                                             Small hospital                                               473050 (19.1)
unit_category_ud, n (%)                      Emergency                                                      79199 (3.2)
                                             OTHER                                                        278422 (11.2)
                                             Surgery                                                      743165 (30.0)
                                             new_internal                                                1376419 (55.6)
response_type_ud, n (%)                      Change                                                         17856 (0.7)
                                             Ignore                                                         78610 (3.2)
                                             No_response_need                                            2380739 (96.1)

                                                                                                                   \
                                                                                                       ANALGESICS
n                                                                                                          424017
hospital_name, n (%)                         BELINSON                                                 25323 (6.0)
                                             CARMEL                                                  46712 (11.0)
                                             EMEK                                                    50483 (11.9)
                                             KAPLAN                                                  71592 (16.9)
                                             MEIR                                                    64616 (15.2)
                                             SHARON                                                   35566 (8.4)
                                             SOROKA                                                 122489 (28.9)
                                             YOSEFTAL                                                  7236 (1.7)
unit_category, n (%)                         Cardiology                                                8851 (2.1)
                                             Emergency                                                19729 (4.7)
                                             Geriatric                                                 4256 (1.0)
                                             Gynecology                                               39670 (9.4)
                                             Hematology                                                2105 (0.5)
                                             Internal                                               131291 (31.0)
                                             Internal-Covid19                                          6310 (1.5)
                                             Nephrology                                                1177 (0.3)
                                             Oncology                                                   578 (0.1)
                                             Surgery                                                210050 (49.5)
age, mean (SD)                                                                                        59.4 (21.2)
gender, n (%)                                FEMALE                                                 223870 (52.8)
                                             MALE                                                   200147 (47.2)
sector, n (%)                                DOCTOR                                                 314103 (74.1)
                                             NURSE                                                  109914 (25.9)
order_origin, n (%)                          Chronic Meds                                             19925 (4.7)
                                             Medication Order                                       219193 (51.7)
                                             Protocol                                               184899 (43.6)
shift_type, n (%)                            afternoon                                              164025 (38.7)
                                             morning                                                174033 (41.0)
                                             night                                                   85959 (20.3)
day, n (%)                                   Friday                                                  48638 (11.5)
                                             Monday                                                  67748 (16.0)
                                             Saturday                                                42535 (10.0)
                                             Sunday                                                  65632 (15.5)
                                             Thursday                                                62323 (14.7)
                                             Tuesday                                                 69263 (16.3)
                                             Wednesday                                               67878 (16.0)
currently_hospitalized, mean (SD)                                                                     20.5 (11.8)
alert_rn_severity, n (%)                     DAM                                                       1969 (0.5)
                                             DDI-Contraindicated Drug Combination                        74 (0.0)
                                             DDI-Moderate Interaction                                 40306 (9.5)
                                             DDI-Severe Interaction                                    1142 (0.3)
                                             DDI-Undetermined Severity - Alternative Therapy...          10 (0.0)
                                             DRC                                                      12493 (2.9)
                                             None                                                   362674 (85.5)
                                             Renal alerts                                                97 (0.0)
                                             Technical alert                                           5252 (1.2)
response_time, mean (SD)                                                                         8977.1 (32465.9)
medication_orders_hospitalization, mean (SD)                                                          18.6 (20.0)
diagnosis_count, mean (SD)                                                                              2.4 (3.3)
charlson_score_age_adj, mean (SD)                                                                       2.9 (2.7)
survival_rate_10y_age_adj, mean (SD)                                                                  65.9 (37.2)
age_category, n (%)                          19-30                                                   55968 (13.2)
                                             31-44                                                   63626 (15.0)
                                             45-55                                                   49247 (11.6)
                                             56-64                                                   51406 (12.1)
                                             65-75                                                   90336 (21.3)
                                             76-85                                                   70802 (16.7)
                                             > 85                                                    42632 (10.1)
chronic_med_count, mean (SD)                                                                            1.6 (3.3)
hospital_days, mean (SD)                                                                                5.7 (8.8)
alert_status, n (%)                          Non_alert                                              362674 (85.5)
                                             Non_stopping_alert                                       41458 (9.8)
                                             Stopping_alert                                           19885 (4.7)
atc_group_ud, n (%)                          ANALGESICS                                            424017 (100.0)
                                             ANTIBACTERIALS FOR SYSTEMIC USE                              0 (0.0)
                                             ANTITHROMBOTIC AGENTS                                        0 (0.0)
                                             CARDIOVASCULAR DRUGS                                         0 (0.0)
                                             DRUGS USED IN DIABETES                                       0 (0.0)
                                             OTHER                                                        0 (0.0)
prescription_day, n (%)                      WEEKDAY                                                332844 (78.5)
                                             WEEKEND                                                 91173 (21.5)
chronic_med_ud, n (%)                        0                                                      404092 (95.3)
                                             <5                                                        3730 (0.9)
                                             >=5                                                      16195 (3.8)
hospital_category, n (%)                     Large hospital                                         147812 (34.9)
                                             Medium hospital                                        186691 (44.0)
                                             Small hospital                                          89514 (21.1)
unit_category_ud, n (%)                      Emergency                                                19729 (4.7)
                                             OTHER                                                   56637 (13.4)
                                             Surgery                                                210050 (49.5)

## Alert analysis

## Alert override analysis

In [23]:
##TODO: get the total number of alerts, overridden alerts, and not overridden alerts
##TODO: plot the distribution of overridden alerts by alert type

In [ ]:
# TODO: get the total number of alerts, overridden alerts, and not overridden alerts

## Analysis of Duplicates

In [24]:
duplicates = df_main_active_adult['id1'].value_counts().sort_values(ascending=False)
duplicates.head()

id1
126485    628
31063     606
147655    561
45        508
32932     503
Name: count, dtype: int64

In [25]:
test_df = df_main_active_adult.loc[df_main_active_adult['id1'].isin(duplicates.index[duplicates > 1])]
test_df.head(20)

,hospital_code,hospital_name,unit_category,severity_level_to_stop_order,medical_record,admission_num,age,gender,sector,time_prescribing_order,alert_drug_header,module_alert_rn,alert_message,alert_severity,order_origin,shift_type,day,currentyl_hospitalized,num_med_order,response_reasons_other_text,response_type,order_details,drug_name_order,chronic_diagnosis,hospital_diagnosis,id1,id2,alert_rn_severity,response_reasons_codes,response_reasons__selected_text,module_severity_rn,mabat_request_time_ms,mabat_response_time_ms,response_time,dosing_subgroup,neodosing_subgroup,atc_count,drug_atc,chronic_drug_count,drug_order_id,medication_orders_hospatalization,diagnosis_count,disease_split,liver_count,hepatic_count,cirrhosis_count,hepatitis_count,portal_hypertension_count,jaundice_count,myocardial_count,heart_failure_count,peripheral_vascular _disease_count,pvd_count,cerebrovascular_count,stroke_count,cerebral_infarction_count,tia_count,cva_count,dementia_count,chronic_ pulmonary _disease_count,copd_count,chronic _obstructive _pulmonary _disease_count,rheumatic_disease_count,fibromyalgia_count,gout_count,arthritis_count,ankylosing_spondylitis_count,scleroderma_count,duodenal_ulcer_count,peptic_ulcer_count,gastric_ulcer_count,diabetes_count,hemiplegia_count,hemiparesis_count,paraplegia_count,renal_count,pyelonephritis_count,hemodialysis_count,kidney_count,ckd_count,arf_count,aki_count,malignancy_count,malignant_count,carcinoma_count,neoplasm_count,adenocarcinoma_count,leukemia_count,aml_count,cml_count,lymphoma_count,hiv_count,metastatic_count,metastasis_count,liver_group_count,pvd_group_count,cerebrovascular_group_count,copd_group_count,gout_group_count,ulcer_group_count,hemiplegia_group_count,renal_group_count,malignancy_group_count,leukemia_group_count,metastatic_group_count,charlson_score,charlson_score_age_adj,survival_rate_10y_age_adj,age_group,age_category,drugs_in_alert_message,alerts_per_order_count,allergy,ddi_contraindicated_severity,ddi_moderate_severity,ddi_severe_severity,dosing,technical_alerts,renal_alerts,neo_dosing,chronic_med_count,date_time_prescribe,hospital_days,diff_time_mabat_y,dosing_duration,dosing_frequency,dosing_max_daily_dose,dosing_message,dosing_single_dose,neo_dosing_duration,neo_dosing_frequency,neo_dosing_max_daily_dose,neo_dosing_message,neo_dosing_single_dose,alert_type,alert_status
0,113,LEVINSTIEN,Surgery,Active Mode,402351,2.022006e+09,36.0,FEMALE,DOCTOR,2022-06-13T09:54:58Z,NaN,NaN,NaN,NaN,Chronic Meds,morning,Monday,49,8,NaN,Non_alert,From Chronic<br/>Oral LANTon 30 mg X2 Per ...,LANTon,NaN,NaN,27861,1032.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,A02BC03,0,113_736747_0,6,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,98.30,adult,31-44,NaN,0.0,0,0,0,0,0,0,0,0,1,2022-06-13,57,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert
1,113,LEVINSTIEN,Surgery,Active Mode,401624,2.022006e+09,42.0,FEMALE,DOCTOR,2022-06-13T12:51:03Z,NaN,NaN,NaN,NaN,Medication Order,morning,Monday,50,11,NaN,Non_alert,Oral TIPTIPOT FERRIPEL-3 50mg/1mL 100 mg X...,TIPTIPOT FERRIPEL-3 50mg/1mL,NaN,NaN,24549,1032.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,B03AB05,0,113_736798,30,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,98.30,adult,31-44,NaN,0.0,0,0,0,0,0,0,0,0,0,2022-06-13,57,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert
2,113,LEVINSTIEN,Surgery,Active Mode,402434,2.022006e+09,45.0,MALE,DOCTOR,2022-06-13T13:12:47Z,NaN,NaN,NaN,NaN,Chronic Meds,morning,Monday,50,6,NaN,Non_alert,From Chronic<br/>INHalation AEROVENT 0.25mg/1m...,AEROVENT 0.25mg/1mL,NaN,NaN,245322,1032.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,R03BB01,0,113_736806_0,9,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,98.30,adult,45-55,NaN,0.0,0,0,0,0,0,0,0,0,7,2022-06-13,1,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert
3,113,LEVINSTIEN,Surgery,Active Mode,402434,2.022006e+09,45.0,MALE,DOCTOR,2022-06-13T13:12:48Z,NaN,NaN,NaN,NaN,Chronic Meds,morning,Monday,50,6,NaN,Non_alert,From Chronic<br/>Oral AVILAC 670mg/mL 30 ml ...,AVILAC 670mg/mL,NaN,NaN,245322,1032.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,A06AD11,0,113_736807_0,9,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,98.30,adult,45-55,NaN,0.0,0,0,0,0,0,0,0,0,7,2022-06-13,1,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert
4,113,LEVINSTIEN,Surgery,Active Mode,402434,2.022006e+09,45.0,MALE,DOCTOR,2022-06-13T13:12:48Z,NaN,NaN,NaN,NaN,Chronic Meds,morning,Monday,50,6,NaN,Non_alert,From Chronic<br/>SubCutaneous CLEXANE 40 mg ...,CLEXANE,NaN,NaN,245322,1032.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,B01AB05,0,113_736808_0,9,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,98.30,adult,45-55,NaN,0.0,0,0,0,0,0,0,0,0,7,2022-06-13,1,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert
5,113,LEVINSTIEN,Surgery,Active Mode,402434,2.022006e+09,45.0,MALE,DOCTOR,2022-06-13T13:12:48Z,NaN,NaN,NaN,NaN,Chronic Meds,morning,Monday,50,6,NaN,Non_alert,From Chronic<br/>Oral OMEPRADEX 40 mg X2 P...,OMEPRADEX,NaN,NaN,245322,1032.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,A02BC01,0,113_736809_0,9,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,98.30,adult,45-55,NaN,0.0,0,0,0,0,0,0,0,0,7,2022-06-13,1,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert
6,113,LEVINSTIEN,Surgery,Active Mode,402434,2.022006e+09,45.0,MALE,DOCTOR,2022-06-13T13:12:48Z,NaN,NaN,NaN,NaN,Chronic Meds,morning,Monday,50,6,NaN,Non_alert,From Chronic<br/>INHalation ventOLIN CFC FREE ...,ventOLIN CFC FREE 0.1mg,NaN,NaN,245322,1032.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,R03AC02,0,113_736810_0,9,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,98.30,adult,45-55,NaN,0.0,0,0,0,0,0,0,0,0,7,2022-06-13,1,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert
7,113,LEVINSTIEN,Surgery,Active Mode,402434,2.022006e+09,45.0,MALE,DOCTOR,2022-06-13T13:14:04Z,NaN,NaN,NaN,NaN,Chronic Meds,morning,Monday,50,7,NaN,Non_alert,From Chronic<br/>Oral AVILAC 670mg/mL 30 ml ...,AVILAC 670mg/mL,NaN,NaN,245322,1032.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,A06AD11,0,113_736811_0,9,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,98.30,adult,45-55,NaN,0.0,0,0,0,0,0,0,0,0,7,2022-06-13,1,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert
8,113,LEVINSTIEN,Surgery,Active Mode,402434,2.022006e+09,45.0,MALE,DOCTOR,2022-06-13T13:14:34Z,NaN,NaN,NaN,NaN,Chronic Meds,morning,Monday,50,7,NaN,Non_alert,From Chronic<br/>SubCutaneous CLEXANE 40 mg ...,CLEXANE,NaN,NaN,245322,1032.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,B01AB05,0,113_736812_0,9,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,98.30,adult,45-55,NaN,0.0,0,0,0,0,0,0,0,0,7,2022-06-13,1,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert
9,113,LEVINSTIEN,Surgery,Active Mode,402434,2.022006e+09,45.0,MALE,DOCTOR,2022-06-13T13:15:48Z,NaN,NaN,NaN,NaN,Medication Order,morning,Monday,50,9,NaN,Non_alert,Oral V-DALGIN 1.25g/5mL 1000 mg S.O.S<br/>...,V-DALGIN 1.25g/5mL,NaN,NaN,245322,1032.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,N02BB02,0,113_736813,9,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,98.30,adult,45-55,NaN,0.0,0,0,0,0,0,0,0,0,0,2022-06-13,1,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert
10,113,LEVINSTIEN,Surgery,Active Mode,402434,2.022006e+09,45.0,MALE,DOCTOR,2022-06-13T13:16:13Z,NaN,NaN,NaN,NaN,Medication Order,morning,Monday,50,9,NaN,Non_alert,Oral bonDORMin 0.25 mg S.O.S<br/>Max Times...,bonDORMin,NaN,NaN,245322,1032.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,N05CD09,0,113_736815,9,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,98.30,adult,45-55,NaN,0.0,0,0,0,0,0,0,0,0,0,2022-06-13,1,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert
11,113,LEVINSTIEN,Surgery,Active Mode,402453,2.022006e+09,77.0,MALE,DOCTOR,2022-06-13T15:45:14Z,NaN,NaN,NaN,NaN,Chronic Meds,afternoon,Monday,50,6,NaN,Non_alert,From Chronic<br/>SubCutaneous INSULIN BASAGLAR...,INSULIN BASAGLAR KWIK PEN,NaN,DIABETES MELLITUS;ESSENTIAL AND OTHER SPECIFIE...,17791,1032.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,A10AE04,0,113_736866_0,6,3,"['DIABETES MELLITUS', 'ESSENTIAL AND OTHER SPE...",0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,3,6,2.25,adult,76-85,NaN,0.0,0,0,0,0,0,0,0,0,5,2022-06-13,1,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert
12,113,LEVINSTIEN,Surgery,Active Mode,402453,2.022006e+09,77.0,MALE,DOCTOR,2022-06-13T15:45:14Z,NaN,NaN,NaN,NaN,Chronic Meds,afternoon,Monday,50,6,NaN,Non_alert,From Chronic<br/>Oral LOSARDEX 50 mg X1 Pe...,LOSARDEX,NaN,DIABETES MELLITUS;ESSENTIAL AND OTHER SPECIFIE...,17791,1032.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,C09CA01,0,113_736867_0,6,3,"['DIABETES MELLITUS', 'ESSENTIAL AND OTHER SPE...",0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,3,6,2.25,adult,76-85,NaN,0.0,0,0,0,0,0,0,0,0,5,2022-06-13,1,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert
13,113,LEVINSTIEN,Surgery,Active Mode,402453,2.022006e+09,77.0,MALE,DOCTOR,2022-06-13T15:45:14Z,NaN,NaN,NaN,NaN,Chronic Meds,afternoon,Monday,50,6,NaN,Non_alert,From Chronic<br/>Oral MIRO 30 mg X1 Per Da...,MIRO,NaN,DIABETES MELLITUS;ESSENTIAL AND OTHER SPECIFIE...,17791,1032.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,N06AX11,0,113_736869_0,6,3,"['DIABETES MELLITUS', 'ESSENTIAL AND OTHER SPE...",0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,3,6,2.25,adult,76-85,NaN,0.0,0,0,0,0,0,0,0,0,5,2022-06-13,1,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert
14,113,LEVINSTIEN,Surgery,Active Mode,402453,2.022006e+09,77.0,MALE,DOCTOR,2022-06-13T15:46:50Z,NaN,NaN,NaN,NaN,Chronic Meds,afternoon,Monday,50,6,NaN,Non_alert,From Chronic<br/>SubCutaneous INSULIN BASAGLAR...,INSULIN BASAGLAR KWIK PEN,NaN,DIABETES MELLITUS;ESSENTIAL AND OTHER SPECIFIE...,17791,1032.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,A10AE04,0,113_736870_0,6,3,"['DIABETES MELLITUS', 'ESSENTIAL AND OTHER SPE...",0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,3,6,2.25,adult,76-85,NaN,0.0,0,0,0,0,0,0,0,0,5,2022-06-13,1,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert
15,113,LEVINSTIEN,Surgery,Active Mode,402453,2.022006e+09,77.0,MALE,DOCTOR,2022-06-13T15:48:26Z,NaN,NaN,NaN,NaN,Chronic Meds,afternoon,Monday,50,7,NaN,Non_alert,From Chronic<br/>Oral MIRO 30 mg X1 Per Da...,MIRO,NaN,DIABETES MELLITUS;ESSENTIAL AND OTHER SPECIFIE...,17791,1032.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,N06AX11,0,113_736872_0,6,3,"['DIABETES MELLITUS', 'ESSENTIAL AND OTHER SPE...",0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,3,6,2.25,adult,76-85,NaN,0.0,0,0,0,0,0,0,0,0,5,2022-06-13,1,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert
16,113,LEVINSTIEN,Surgery,Active Mode,402453,2.022006e+09,77.0,MALE,DOCTOR,2022-06-13T15:50:17Z,NaN,NaN,NaN,NaN,Medication Order,afternoon,Monday,50,7,NaN,Non_alert,SubCutaneous INSULIN APIDRA 9999 unit X3 P...,INSULIN APIDRA,NaN,DIABETES MELLITUS;ESSENTIAL AND OTHER SPECIFIE...,17791,1032.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,A10AB06,0,113_736875,6,3,"['DIABETES MELLITUS', 'ESSENTIAL AND OTHER SPE...",0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,3,6,2.25,adult,76-85,NaN,0.0,0,0,0,0,0,0,0,0,0,2022-06-13,1,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert
17,113,LEVINSTIEN,Surgery,Active Mode,402143,2.022006e+09,77.0,FEMALE,DOCTOR,2022-06-13T16:28:50Z,NaN,NaN,NaN,NaN,Medication Order,afternoon,Monday,50,1,NaN,Non_alert,"SubCutaneous CLEXANE 40 mg X1 Per Day, Eve...",CLEXANE,NaN,"CATARACT;Fracture of Femur, Subcapital - SP;Fr...",13839,7355.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,B01AB05,0,113_736887,13,3,"['CATARACT', 'FRACTURE OF FEMUR, SUBCAPITAL - ...",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,77.48,adult,76-85,NaN,0.0,0,0,0,0,0,0,0,0,0,2022-06-13,6,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert
18,113,LEVINSTIEN,Surgery,Active Mode,402143,2.022006e+09,77.0,FEMALE,DOCTOR,2022-06-13T16:30:06Z,NaN,NaN,NaN,NaN,Medication Order,afternoon,Monday,50,3,NaN,Non_alert,"Oral LIPITOR 80 mg X1 Per Day, Every Day <...",LIPITOR,NaN,"CATARACT;Fracture of Femur, Subcapital - SP;Fr...",13839,7355.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,C10AA05,0,113_736888,13,3,"['CATARACT', 'FRACTURE OF FEMUR, SUBCAPITAL - ...",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,77.48,adult,76-85,NaN,0.0,0,0,0,0,0,0,0,0,0,2022-06-13,6,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert
19,113,LEVINSTIEN,Surgery,Active Mode,402143,2.022006e+09,77.0,FEMALE,DOCTOR,2022-06-13T16:34:39Z,NaN,NaN,NaN,NaN,Medication Order,afternoon,Monday,50,4,NaN,Non_alert,"Oral LANTon 30 mg X2 Per Day, Every Day <B...",LANTon,NaN,"CATARACT;Fracture of Femur, Subcapital - SP;Fr...",13839,7355.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,A02BC03,0,113_736891,13,3,"['CATARACT', 'FRACTURE OF FEMUR, SUBCAPITAL - ...",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,77.48,adult,76-85,NaN,0.0,0,0,0,0,0,0,0,0,0,2022-06-13,6,NaN,0,0,0,0,0,0,0,0,0,0,Non_alert,Non_alert

## Table alert module per months: Dosing & Drug-drug interaction and allergy alert data (percent of orders triggering an alert)

In [ ]:
from tableone import TableOne

# Create month column from date_time_prescribe for grouping
# Convert to datetime if not already

if df_main_active_adult['date_time_prescribe'].dtype == 'object':
    df_main_active_adult['prescription_month'] = pd.to_datetime(df_main_active_adult['date_time_prescribe']).dt.to_period('M').astype(str)
else:
    df_main_active_adult['prescription_month'] = pd.to_datetime(df_main_active_adult['date_time_prescribe']).dt.to_period('M').astype(str)

# Define categorical variables
categorical_vars = [
    "dosing_single_dose",
    "dosing_frequency",
    "dosing_max_daily_dose",
    "renal_alerts",
    "ddi_contraindicated_severity",
    "ddi_severe_severity",
    "ddi_moderate_severity",
    "allergy",
    "technical_alerts"
]


# Add at least one continuous variable (TableOne requires continuous vars when using groupby)
# Using hospital_days as a continuous variable
continuous_vars = ['hospital_days']

# Generate summary table grouped by month
alert_table = TableOne(
    df_main_active_adult,
    categorical=categorical_vars,
    continuous=continuous_vars,
    groupby="prescription_month",
    pval=False,
    missing=True
)

# Print the table
print(alert_table.tabulate(tablefmt="pipe"))



#previous one
    #alert_table = TableOne(
    # df_main_active_adult,
    # categorical=categorical_vars,
    #continuous=[],
    #groupby="date_time_prescribe",
    #pval=False,  # Add p-values
    #missing=True  # Show missing values
#)

# Print the table
#print(alert_table.tabulate(tablefmt="pipe"))

NameError: name 'df_main_active_adult' is not defined

In [49]:
print(df_main_active_adult['date_time_prescribe'].dtype)

object

In [ ]:
df_main_active_adult.columns.to_list()

In [9]:
test_df = pd.read_csv('alert_analysis/data/main_data_2022/df_main_active_adult_py_version.csv')
test_df.shape

(2506589, 169)

In [10]:
test_df['Hospital_cat'].value_counts()

Hospital_cat
24     688747
28     416000
23     394886
26     310498
237    288908
20     223398
22     157020
19      27132
Name: count, dtype: int64

In [8]:
test_df['Hospital_cat'].dtype

dtype('int64')

In [19]:
test_df['ATC_GROUP']

KeyError: 'ATC_GROUP'