In [1]:
#!pip install tableone
import pandas as pd
from tableone import TableOne
import warnings

#import ace_tools as tools
warnings.filterwarnings("ignore")
pd.set_option('display.max_rows', 200)  # Set to 200 or more, higher than 105
pd.set_option('display.max_columns', None)  # Show all columns if needed

In [2]:
patient_level_df = pd.read_csv('alert_analysis/data/main_data_2022/df_patients_level_data.csv')
print(patient_level_df.shape)
patient_level_df.head(10)

(155747, 115)

,id1,gender,age,age_category,unit_category_ud,chronic_med_ud,response_reasons_other_text,dosing_frequency_sum,dosing_single_dose_sum,dosing_max_daily_dose_sum,neo_dosing_frequency_sum,neo_dosing_single_dose_sum,neo_dosing_max_daily_dose_sum,unique_hospitals,survival_rate_10y_age_adj_mean,charlson_score_age_adj_mean,hospital_days_mean,kidney_disease,hepatic_disease,diabetes_disease,ischemic_heart_disease,copd_disease,cerebrovascular_disease,peptic_ulcer_disease,dementia_disease,oncological_disease,hemato_oncological_disease,hypertension_disease,atrial_fibrillation_disease,hyperlipidemia_disease,congestive_heart_failure_disease,obesity_disease,atc_count_mean,chronic_drug_count_mean,diagnosis_count_mean,pvd_count_mean,pvd_group_count_mean,alerts_per_order_count_mean,chronic_med_count_mean,unit_Internal,unit_Surgery,unit_Gynecology,unit_Cardiology,unit_Emergency,unit_Internal-Covid19,unit_Geriatric,unit_Hematology,unit_Nephrology,unit_Oncology,is_Non_alert,is_Non_Error_alert,is_Error_Alert,is_No_response_need,is_Ignore,is_Change,liver_count_bool,hepatic_count_bool,cirrhosis_count_bool,hepatitis_count_bool,portal_hypertension_count_bool,jaundice_count_bool,myocardial_count_bool,heart_failure_count_bool,peripheral_vascular _disease_count_bool,cerebrovascular_count_bool,stroke_count_bool,cerebral_infarction_count_bool,tia_count_bool,cva_count_bool,dementia_count_bool,chronic_ pulmonary _disease_count_bool,copd_count_bool,chronic _obstructive _pulmonary _disease_count_bool,rheumatic_disease_count_bool,fibromyalgia_count_bool,gout_count_bool,arthritis_count_bool,ankylosing_spondylitis_count_bool,scleroderma_count_bool,duodenal_ulcer_count_bool,peptic_ulcer_count_bool,gastric_ulcer_count_bool,diabetes_count_bool,hemiplegia_count_bool,hemiparesis_count_bool,paraplegia_count_bool,renal_count_bool,pyelonephritis_count_bool,hemodialysis_count_bool,kidney_count_bool,ckd_count_bool,arf_count_bool,aki_count_bool,malignancy_count_bool,malignant_count_bool,carcinoma_count_bool,neoplasm_count_bool,adenocarcinoma_count_bool,leukemia_count_bool,aml_count_bool,cml_count_bool,lymphoma_count_bool,hiv_count_bool,metastatic_count_bool,metastasis_count_bool,liver_group_count_bool,cerebrovascular_group_count_bool,copd_group_count_bool,gout_group_count_bool,ulcer_group_count_bool,hemiplegia_group_count_bool,renal_group_count_bool,malignancy_group_count_bool,leukemia_group_count_bool,metastatic_group_count_bool
0,2,FEMALE,80.0,76-85,Surgery,0,NaN,0,0,0,0,0,0,1,21.36,5.0,1.000000,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,1.333333,0.000000,4.0,0.0,0.0,0.000000,0.000000,0,1,0,0,0,0,0,0,0,0,3,0,0,3,0,0,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
1,3,MALE,74.0,65-75,Surgery,0,NaN,0,0,0,0,0,0,1,77.48,3.0,2.714286,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.000000,0.000000,0.0,0.0,0.0,0.142857,0.000000,0,1,0,0,0,0,0,0,0,0,12,2,0,14,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,4,FEMALE,76.0,76-85,new_internal,>=5,NaN,0,0,0,0,0,0,1,2.25,6.0,1.758621,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1.034483,0.000000,3.0,0.0,0.0,0.000000,2.965517,1,1,0,0,0,0,0,0,0,0,29,0,0,29,0,0,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False
3,5,FEMALE,77.0,76-85,Surgery,0,NaN,0,0,0,0,0,0,1,77.48,3.0,1.687500,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.062500,0.000000,0.0,0.0,0.0,0.062500,0.062500,0,1,0,0,1,0,0,0,0,0,15,1,0,15,1,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,7,MALE,75.0,65-75,new_internal,0,NaN,0,0,0,0,0,0,1,77.48,3.0,1.600000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,1,0,0,0,0,0,0,0,0,0,5,0,0,5,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,8,FEMALE,74.0,65-75,Surgery,<5,NaN,0,0,0,0,0,0,1,77.48,3.0,1.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.000000,0.000000,0.0,0.0,0.0,0.250000,1.000000,0,1,0,0,0,0,0,0,0,0,3,1,0,4,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,9,FEMALE,74.0,65-75,new_internal,0,NaN,0,0,0,0,0,0,1,77.48,3.0,11.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,1,0,0,0,0,0,0,0,0,0,15,0,0,15,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,10,MALE,80.0,76-85,new_internal,>=5,NaN,0,0,0,0,0,0,1,2.25,6.0,1.521739,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.021739,0.021739,1.0,0.0,0.0,0.108696,5.369565,1,0,0,1,0,0,0,0,0,0,41,3,2,44,2,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
8,11,MALE,74.0,65-75,Surgery,0,NaN,0,0,0,0,0,0,1,21.36,5.0,2.777778,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1.055556,0.000000,4.0,0.0,0.0,0.000000,2.055556,0,1,0,0,0,0,0,0,0,0,18,0,0,18,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,12,MALE,74.0,65-75,Surgery,0,קבוע מינון כלייתי,1,0,1,0,0,0,1,77.48,3.0,2.243243,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.000000,0.000000,0.0,0.0,0.0,0.297297,3.945946,1,1,0,0,0,0,0,0,0,0,27,9,1,36,1,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [3]:
patient_level_df.columns.to_list()

['id1',
 'gender',
 'age',
 'age_category',
 'unit_category_ud',
 'chronic_med_ud',
 'response_reasons_other_text',
 'dosing_frequency_sum',
 'dosing_single_dose_sum',
 'dosing_max_daily_dose_sum',
 'neo_dosing_frequency_sum',
 'neo_dosing_single_dose_sum',
 'neo_dosing_max_daily_dose_sum',
 'unique_hospitals',
 'survival_rate_10y_age_adj_mean',
 'charlson_score_age_adj_mean',
 'hospital_days_mean',
 'kidney_disease',
 'hepatic_disease',
 'diabetes_disease',
 'ischemic_heart_disease',
 'copd_disease',
 'cerebrovascular_disease',
 'peptic_ulcer_disease',
 'dementia_disease',
 'oncological_disease',
 'hemato_oncological_disease',
 'hypertension_disease',
 'atrial_fibrillation_disease',
 'hyperlipidemia_disease',
 'congestive_heart_failure_disease',
 'obesity_disease',
 'atc_count_mean',
 'chronic_drug_count_mean',
 'diagnosis_count_mean',
 'pvd_count_mean',
 'pvd_group_count_mean',
 'alerts_per_order_count_mean',
 'chronic_med_count_mean',
 'unit_Internal',
 'unit_Surgery',
 'unit_Gynecology',
 'unit_Cardiology',
 'unit_Emergency',
 'unit_Internal-Covid19',
 'unit_Geriatric',
 'unit_Hematology',
 'unit_Nephrology',
 'unit_Oncology',
 'is_Non_alert',
 'is_Non_Error_alert',
 'is_Error_Alert',
 'is_No_response_need',
 'is_Ignore',
 'is_Change',
 'liver_count_bool',
 'hepatic_count_bool',
 'cirrhosis_count_bool',
 'hepatitis_count_bool',
 'portal_hypertension_count_bool',
 'jaundice_count_bool',
 'myocardial_count_bool',
 'heart_failure_count_bool',
 'peripheral_vascular _disease_count_bool',
 'cerebrovascular_count_bool',
 'stroke_count_bool',
 'cerebral_infarction_count_bool',
 'tia_count_bool',
 'cva_count_bool',
 'dementia_count_bool',
 'chronic_ pulmonary _disease_count_bool',
 'copd_count_bool',
 'chronic _obstructive _pulmonary _disease_count_bool',
 'rheumatic_disease_count_bool',
 'fibromyalgia_count_bool',
 'gout_count_bool',
 'arthritis_count_bool',
 'ankylosing_spondylitis_count_bool',
 'scleroderma_count_bool',
 'duodenal_ulcer_count_bool',
 'peptic_ulcer_count_bool',
 'gastric_ulcer_count_bool',
 'diabetes_count_bool',
 'hemiplegia_count_bool',
 'hemiparesis_count_bool',
 'paraplegia_count_bool',
 'renal_count_bool',
 'pyelonephritis_count_bool',
 'hemodialysis_count_bool',
 'kidney_count_bool',
 'ckd_count_bool',
 'arf_count_bool',
 'aki_count_bool',
 'malignancy_count_bool',
 'malignant_count_bool',
 'carcinoma_count_bool',
 'neoplasm_count_bool',
 'adenocarcinoma_count_bool',
 'leukemia_count_bool',
 'aml_count_bool',
 'cml_count_bool',
 'lymphoma_count_bool',
 'hiv_count_bool',
 'metastatic_count_bool',
 'metastasis_count_bool',
 'liver_group_count_bool',
 'cerebrovascular_group_count_bool',
 'copd_group_count_bool',
 'gout_group_count_bool',
 'ulcer_group_count_bool',
 'hemiplegia_group_count_bool',
 'renal_group_count_bool',
 'malignancy_group_count_bool',
 'leukemia_group_count_bool',
 'metastatic_group_count_bool']

In [6]:
# Define categorical and continuous variables
categorical_vars = [
    "age_category",
    'unit_category_ud',  # Added: unit category
    'unit_Internal',
    'unit_Internal-Covid19',
    'unit_Surgery',
    'unit_Gynecology',
    'unit_Cardiology',
    'unit_Emergency',
    'unit_Geriatric',
    'unit_Hematology',
    'unit_Nephrology',
    'unit_Oncology',
    'gender',
    'chronic_med_ud',  # Added: chronic medication
    # Disease columns - Added
    'kidney_disease',
    'hepatic_disease',
    'diabetes_disease',
    'ischemic_heart_disease',
    'copd_disease',
    'cerebrovascular_disease',
    'peptic_ulcer_disease',
    'dementia_disease',
    'oncological_disease',
    'hemato_oncological_disease',
    'hypertension_disease',
    'atrial_fibrillation_disease',
    'hyperlipidemia_disease',
    'congestive_heart_failure_disease',
    'obesity_disease',
]

continuous_vars = [
    "age",
    'survival_rate_10y_age_adj_mean',
    'charlson_score_age_adj_mean',
    'hospital_days_mean',
    'chronic_med_count_mean',
    'diagnosis_count_mean',
]

#non_normal = ["age"]

# Convert categorical columns to strings to avoid type comparison errors
# This ensures all categorical values are strings before TableOne processes them
for col in categorical_vars:
    if col in patient_level_df.columns:
        patient_level_df[col] = patient_level_df[col].astype(str)

# Generate summary table
table = TableOne(
    patient_level_df,
    categorical=categorical_vars,
    groupby="gender",
    continuous=continuous_vars,
    #nonnormal=non_normal,
    pval=True,  # Add p-values
    missing=False  # don't Show missing values
)

# Print the table
print(table.tabulate(tablefmt="pipe"))

|                                           |              | Overall       | FEMALE        | MALE          | P-Value   |
|:------------------------------------------|:-------------|:--------------|:--------------|:--------------|:----------|
| n                                         |              | 155747        | 84479         | 71268         |           |
| gender, n (%)                             | FEMALE       | 84479 (54.2)  | 84479 (100.0) | 0 (0.0)       | <0.001    |
|                                           | MALE         | 71268 (45.8)  | 0 (0.0)       | 71268 (100.0) |           |
| age, mean (SD)                            |              | 56.9 (21.7)   | 54.6 (22.8)   | 59.6 (20.0)   | <0.001    |
| age_category, n (%)                       | 19-30        | 25389 (16.3)  | 17223 (20.4)  | 8166 (11.5)   | <0.001    |
|                                           | 31-44        | 26837 (17.2)  | 17305 (20.5)  | 9532 (13.4)   |           |
|                                           | 45-55        | 17947 (11.5)  | 8272 (9.8)    | 9675 (13.6)   |           |
|                                           | 56-64        | 17921 (11.5)  | 7796 (9.2)    | 10125 (14.2)  |           |
|                                           | 65-75        | 30613 (19.7)  | 13938 (16.5)  | 16675 (23.4)  |           |
|                                           | 76-85        | 23257 (14.9)  | 11909 (14.1)  | 11348 (15.9)  |           |
|                                           | > 85         | 13783 (8.8)   | 8036 (9.5)    | 5747 (8.1)    |           |
| unit_category_ud, n (%)                   | Emergency    | 20354 (13.1)  | 13171 (15.6)  | 7183 (10.1)   | <0.001    |
|                                           | OTHER        | 22282 (14.3)  | 18468 (21.9)  | 3814 (5.4)    |           |
|                                           | Surgery      | 49879 (32.0)  | 21854 (25.9)  | 28025 (39.3)  |           |
|                                           | new_internal | 63232 (40.6)  | 30986 (36.7)  | 32246 (45.2)  |           |
| chronic_med_ud, n (%)                     | 0            | 125098 (80.3) | 70709 (83.7)  | 54389 (76.3)  | <0.001    |
|                                           | <5           | 8508 (5.5)    | 3886 (4.6)    | 4622 (6.5)    |           |
|                                           | >=5          | 22141 (14.2)  | 9884 (11.7)   | 12257 (17.2)  |           |
| survival_rate_10y_age_adj_mean, mean (SD) |              | 71.3 (34.9)   | 74.1 (33.8)   | 68.0 (35.9)   | <0.001    |
| charlson_score_age_adj_mean, mean (SD)    |              | 2.4 (2.6)     | 2.2 (2.5)     | 2.8 (2.6)     | <0.001    |
| hospital_days_mean, mean (SD)             |              | 2.8 (3.9)     | 2.6 (3.6)     | 3.0 (4.3)     | <0.001    |
| kidney_disease, n (%)                     | 0            | 147868 (94.9) | 81577 (96.6)  | 66291 (93.0)  | <0.001    |
|                                           | 1            | 7879 (5.1)    | 2902 (3.4)    | 4977 (7.0)    |           |
| hepatic_disease, n (%)                    | 0            | 153640 (98.6) | 83357 (98.7)  | 70283 (98.6)  | 0.370     |
|                                           | 1            | 2107 (1.4)    | 1122 (1.3)    | 985 (1.4)     |           |
| diabetes_disease, n (%)                   | 0            | 133114 (85.5) | 74010 (87.6)  | 59104 (82.9)  | <0.001    |
|                                           | 1            | 22633 (14.5)  | 10469 (12.4)  | 12164 (17.1)  |           |
| ischemic_heart_disease, n (%)             | 0            | 144715 (92.9) | 81659 (96.7)  | 63056 (88.5)  | <0.001    |
|                                           | 1            | 11032 (7.1)   | 2820 (3.3)    | 8212 (11.5)   |           |
| copd_disease, n (%)                       | 0            | 152506 (97.9) | 83372 (98.7)  | 69134 (97.0)  | <0.001    |
|                                           | 1            | 3241 (2.1)    | 1107 (1.3)    | 2134 (3.0)    |           |
| cerebrovascular_disease, n (%)            | 0            | 128694 (82.6) | 71621 (84.8)  | 57073 (80.1)  | <0.001    |
|                                           | 1            | 27053 (17.4)  | 12858 (15.2)  | 14195 (19.9)  |           |
| peptic_ulcer_disease, n (%)               | 0            | 155136 (99.6) | 84250 (99.7)  | 70886 (99.5)  | <0.001    |
|                                           | 1            | 611 (0.4)     | 229 (0.3)     | 382 (0.5)     |           |
| dementia_disease, n (%)                   | 0            | 153695 (98.7) | 83188 (98.5)  | 70507 (98.9)  | <0.001    |
|                                           | 1            | 2052 (1.3)    | 1291 (1.5)    | 761 (1.1)     |           |
| oncological_disease, n (%)                | 0            | 149666 (96.1) | 81512 (96.5)  | 68154 (95.6)  | <0.001    |
|                                           | 1            | 6081 (3.9)    | 2967 (3.5)    | 3114 (4.4)    |           |
| hemato_oncological_disease, n (%)         | 0            | 154601 (99.3) | 83976 (99.4)  | 70625 (99.1)  | <0.001    |
|                                           | 1            | 1146 (0.7)    | 503 (0.6)     | 643 (0.9)     |           |
| hypertension_disease, n (%)               | 0            | 121091 (77.7) | 67793 (80.2)  | 53298 (74.8)  | <0.001    |
|                                           | 1            | 34656 (22.3)  | 16686 (19.8)  | 17970 (25.2)  |           |
| atrial_fibrillation_disease, n (%)        | 0            | 148588 (95.4) | 80872 (95.7)  | 67716 (95.0)  | <0.001    |
|                                           | 1            | 7159 (4.6)    | 3607 (4.3)    | 3552 (5.0)    |           |
| hyperlipidemia_disease, n (%)             | 0            | 129284 (83.0) | 72703 (86.1)  | 56581 (79.4)  | <0.001    |
|                                           | 1            | 26463 (17.0)  | 11776 (13.9)  | 14687 (20.6)  |           |
| congestive_heart_failure_disease, n (%)   | 0            | 151548 (97.3) | 82736 (97.9)  | 68812 (96.6)  | <0.001    |
|                                           | 1            | 4199 (2.7)    | 1743 (2.1)    | 2456 (3.4)    |           |
| obesity_disease, n (%)                    | 0            | 146592 (94.1) | 79359 (93.9)  | 67233 (94.3)  | <0.001    |
|                                           | 1            | 9155 (5.9)    | 5120 (6.1)    | 4035 (5.7)    |           |
| diagnosis_count_mean, mean (SD)           |              | 1.9 (2.9)     | 1.6 (2.8)     | 2.2 (3.1)     | <0.001    |
| chronic_med_count_mean, mean (SD)         |              | 1.4 (2.7)     | 1.2 (2.5)     | 1.8 (2.9)     | <0.001    |
| unit_Internal, n (%)                      | 0            | 88288 (56.7)  | 51842 (61.4)  | 36446 (51.1)  | <0.001    |
|                                           | 1            | 67459 (43.3)  | 32637 (38.6)  | 34822 (48.9)  |           |
| unit_Surgery, n (%)                       | 0            | 101110 (64.9) | 60468 (71.6)  | 40642 (57.0)  | <0.001    |
|                                           | 1            | 54637 (35.1)  | 24011 (28.4)  | 30626 (43.0)  |           |
| unit_Gynecology, n (%)                    | 0            | 137383 (88.2) | 66115 (78.3)  | 71268 (100.0) | <0.001    |
|                                           | 1            | 18364 (11.8)  | 18364 (21.7)  | 0 (0.0)       |           |
| unit_Cardiology, n (%)                    | 0            | 149638 (96.1) | 82709 (97.9)  | 66929 (93.9)  | <0.001    |
|                                           | 1            | 6109 (3.9)    | 1770 (2.1)    | 4339 (6.1)    |           |
| unit_Emergency, n (%)                     | 0            | 126124 (81.0) | 65632 (77.7)  | 60492 (84.9)  | <0.001    |
|                                           | 1            | 29623 (19.0)  | 18847 (22.3)  | 10776 (15.1)  |           |
| unit_Internal-Covid19, n (%)              | 0            | 151401 (97.2) | 82241 (97.4)  | 69160 (97.0)  | <0.001    |
|                                           | 1            | 4346 (2.8)    | 2238 (2.6)    | 2108 (3.0)    |           |
| unit_Geriatric, n (%)                     | 0            | 154857 (99.4) | 83952 (99.4)  | 70905 (99.5)  | 0.003     |
|                                           | 1            | 890 (0.6)     | 527 (0.6)     | 363 (0.5)     |           |
| unit_Hematology, n (%)                    | 0            | 155412 (99.8) | 84334 (99.8)  | 71078 (99.7)  | <0.001    |
|                                           | 1            | 335 (0.2)     | 145 (0.2)     | 190 (0.3)     |           |
| unit_Nephrology, n (%)                    | 0            | 154818 (99.4) | 84080 (99.5)  | 70738 (99.3)  | <0.001    |
|                                           | 1            | 929 (0.6)     | 399 (0.5)     | 530 (0.7)     |           |
| unit_Oncology, n (%)                      | 0            | 155627 (99.9) | 84417 (99.9)  | 71210 (99.9)  | 0.635     |
|                                           | 1            | 120 (0.1)     | 62 (0.1)      | 58 (0.1)      |           |

In [7]:
# Generate summary table

# continuous_vars.append('gender')

table = TableOne(
    patient_level_df,
    groupby="gender",
    categorical=categorical_vars,
    continuous=continuous_vars,
    nonnormal=continuous_vars,
    pval=True,  # Add p-values
    missing=False  # don't Show missing values
)

# Print the table
print(table.tabulate(tablefmt="pipe"))

|                                                |              | Overall          | FEMALE           | MALE             | P-Value   |
|:-----------------------------------------------|:-------------|:-----------------|:-----------------|:-----------------|:----------|
| n                                              |              | 155747           | 84479            | 71268            |           |
| gender, n (%)                                  | FEMALE       | 84479 (54.2)     | 84479 (100.0)    | 0 (0.0)          | <0.001    |
|                                                | MALE         | 71268 (45.8)     | 0 (0.0)          | 71268 (100.0)    |           |
| age, median [Q1,Q3]                            |              | 60.0 [37.0,75.0] | 55.0 [33.0,75.0] | 63.0 [45.0,75.0] | <0.001    |
| age_category, n (%)                            | 19-30        | 25389 (16.3)     | 17223 (20.4)     | 8166 (11.5)      | <0.001    |
|                                                | 31-44        | 26837 (17.2)     | 17305 (20.5)     | 9532 (13.4)      |           |
|                                                | 45-55        | 17947 (11.5)     | 8272 (9.8)       | 9675 (13.6)      |           |
|                                                | 56-64        | 17921 (11.5)     | 7796 (9.2)       | 10125 (14.2)     |           |
|                                                | 65-75        | 30613 (19.7)     | 13938 (16.5)     | 16675 (23.4)     |           |
|                                                | 76-85        | 23257 (14.9)     | 11909 (14.1)     | 11348 (15.9)     |           |
|                                                | > 85         | 13783 (8.8)      | 8036 (9.5)       | 5747 (8.1)       |           |
| unit_category_ud, n (%)                        | Emergency    | 20354 (13.1)     | 13171 (15.6)     | 7183 (10.1)      | <0.001    |
|                                                | OTHER        | 22282 (14.3)     | 18468 (21.9)     | 3814 (5.4)       |           |
|                                                | Surgery      | 49879 (32.0)     | 21854 (25.9)     | 28025 (39.3)     |           |
|                                                | new_internal | 63232 (40.6)     | 30986 (36.7)     | 32246 (45.2)     |           |
| chronic_med_ud, n (%)                          | 0            | 125098 (80.3)    | 70709 (83.7)     | 54389 (76.3)     | <0.001    |
|                                                | <5           | 8508 (5.5)       | 3886 (4.6)       | 4622 (6.5)       |           |
|                                                | >=5          | 22141 (14.2)     | 9884 (11.7)      | 12257 (17.2)     |           |
| survival_rate_10y_age_adj_mean, median [Q1,Q3] |              | 90.2 [53.4,98.3] | 95.9 [53.4,98.3] | 90.2 [53.4,98.3] | <0.001    |
| charlson_score_age_adj_mean, median [Q1,Q3]    |              | 2.0 [0.0,4.0]    | 1.0 [0.0,4.0]    | 2.0 [0.0,4.0]    | <0.001    |
| hospital_days_mean, median [Q1,Q3]             |              | 1.7 [1.0,3.0]    | 1.5 [1.0,3.0]    | 1.9 [1.0,3.0]    | <0.001    |
| kidney_disease, n (%)                          | 0            | 147868 (94.9)    | 81577 (96.6)     | 66291 (93.0)     | <0.001    |
|                                                | 1            | 7879 (5.1)       | 2902 (3.4)       | 4977 (7.0)       |           |
| hepatic_disease, n (%)                         | 0            | 153640 (98.6)    | 83357 (98.7)     | 70283 (98.6)     | 0.370     |
|                                                | 1            | 2107 (1.4)       | 1122 (1.3)       | 985 (1.4)        |           |
| diabetes_disease, n (%)                        | 0            | 133114 (85.5)    | 74010 (87.6)     | 59104 (82.9)     | <0.001    |
|                                                | 1            | 22633 (14.5)     | 10469 (12.4)     | 12164 (17.1)     |           |
| ischemic_heart_disease, n (%)                  | 0            | 144715 (92.9)    | 81659 (96.7)     | 63056 (88.5)     | <0.001    |
|                                                | 1            | 11032 (7.1)      | 2820 (3.3)       | 8212 (11.5)      |           |
| copd_disease, n (%)                            | 0            | 152506 (97.9)    | 83372 (98.7)     | 69134 (97.0)     | <0.001    |
|                                                | 1            | 3241 (2.1)       | 1107 (1.3)       | 2134 (3.0)       |           |
| cerebrovascular_disease, n (%)                 | 0            | 128694 (82.6)    | 71621 (84.8)     | 57073 (80.1)     | <0.001    |
|                                                | 1            | 27053 (17.4)     | 12858 (15.2)     | 14195 (19.9)     |           |
| peptic_ulcer_disease, n (%)                    | 0            | 155136 (99.6)    | 84250 (99.7)     | 70886 (99.5)     | <0.001    |
|                                                | 1            | 611 (0.4)        | 229 (0.3)        | 382 (0.5)        |           |
| dementia_disease, n (%)                        | 0            | 153695 (98.7)    | 83188 (98.5)     | 70507 (98.9)     | <0.001    |
|                                                | 1            | 2052 (1.3)       | 1291 (1.5)       | 761 (1.1)        |           |
| oncological_disease, n (%)                     | 0            | 149666 (96.1)    | 81512 (96.5)     | 68154 (95.6)     | <0.001    |
|                                                | 1            | 6081 (3.9)       | 2967 (3.5)       | 3114 (4.4)       |           |
| hemato_oncological_disease, n (%)              | 0            | 154601 (99.3)    | 83976 (99.4)     | 70625 (99.1)     | <0.001    |
|                                                | 1            | 1146 (0.7)       | 503 (0.6)        | 643 (0.9)        |           |
| hypertension_disease, n (%)                    | 0            | 121091 (77.7)    | 67793 (80.2)     | 53298 (74.8)     | <0.001    |
|                                                | 1            | 34656 (22.3)     | 16686 (19.8)     | 17970 (25.2)     |           |
| atrial_fibrillation_disease, n (%)             | 0            | 148588 (95.4)    | 80872 (95.7)     | 67716 (95.0)     | <0.001    |
|                                                | 1            | 7159 (4.6)       | 3607 (4.3)       | 3552 (5.0)       |           |
| hyperlipidemia_disease, n (%)                  | 0            | 129284 (83.0)    | 72703 (86.1)     | 56581 (79.4)     | <0.001    |
|                                                | 1            | 26463 (17.0)     | 11776 (13.9)     | 14687 (20.6)     |           |
| congestive_heart_failure_disease, n (%)        | 0            | 151548 (97.3)    | 82736 (97.9)     | 68812 (96.6)     | <0.001    |
|                                                | 1            | 4199 (2.7)       | 1743 (2.1)       | 2456 (3.4)       |           |
| obesity_disease, n (%)                         | 0            | 146592 (94.1)    | 79359 (93.9)     | 67233 (94.3)     | <0.001    |
|                                                | 1            | 9155 (5.9)       | 5120 (6.1)       | 4035 (5.7)       |           |
| diagnosis_count_mean, median [Q1,Q3]           |              | 0.0 [0.0,3.0]    | 0.0 [0.0,2.8]    | 0.0 [0.0,4.0]    | <0.001    |
| chronic_med_count_mean, median [Q1,Q3]         |              | 0.0 [0.0,2.0]    | 0.0 [0.0,1.2]    | 0.0 [0.0,2.7]    | <0.001    |
| unit_Internal, n (%)                           | 0            | 88288 (56.7)     | 51842 (61.4)     | 36446 (51.1)     | <0.001    |
|                                                | 1            | 67459 (43.3)     | 32637 (38.6)     | 34822 (48.9)     |           |
| unit_Surgery, n (%)                            | 0            | 101110 (64.9)    | 60468 (71.6)     | 40642 (57.0)     | <0.001    |
|                                                | 1            | 54637 (35.1)     | 24011 (28.4)     | 30626 (43.0)     |           |
| unit_Gynecology, n (%)                         | 0            | 137383 (88.2)    | 66115 (78.3)     | 71268 (100.0)    | <0.001    |
|                                                | 1            | 18364 (11.8)     | 18364 (21.7)     | 0 (0.0)          |           |
| unit_Cardiology, n (%)                         | 0            | 149638 (96.1)    | 82709 (97.9)     | 66929 (93.9)     | <0.001    |
|                                                | 1            | 6109 (3.9)       | 1770 (2.1)       | 4339 (6.1)       |           |
| unit_Emergency, n (%)                          | 0            | 126124 (81.0)    | 65632 (77.7)     | 60492 (84.9)     | <0.001    |
|                                                | 1            | 29623 (19.0)     | 18847 (22.3)     | 10776 (15.1)     |           |
| unit_Internal-Covid19, n (%)                   | 0            | 151401 (97.2)    | 82241 (97.4)     | 69160 (97.0)     | <0.001    |
|                                                | 1            | 4346 (2.8)       | 2238 (2.6)       | 2108 (3.0)       |           |
| unit_Geriatric, n (%)                          | 0            | 154857 (99.4)    | 83952 (99.4)     | 70905 (99.5)     | 0.003     |
|                                                | 1            | 890 (0.6)        | 527 (0.6)        | 363 (0.5)        |           |
| unit_Hematology, n (%)                         | 0            | 155412 (99.8)    | 84334 (99.8)     | 71078 (99.7)     | <0.001    |
|                                                | 1            | 335 (0.2)        | 145 (0.2)        | 190 (0.3)        |           |
| unit_Nephrology, n (%)                         | 0            | 154818 (99.4)    | 84080 (99.5)     | 70738 (99.3)     | <0.001    |
|                                                | 1            | 929 (0.6)        | 399 (0.5)        | 530 (0.7)        |           |
| unit_Oncology, n (%)                           | 0            | 155627 (99.9)    | 84417 (99.9)     | 71210 (99.9)     | 0.635     |
|                                                | 1            | 120 (0.1)        | 62 (0.1)         | 58 (0.1)         |           |

In [8]:
print(min(patient_level_df['age']))
print(max(patient_level_df['age']))

19.0
123.0

In [9]:
patient_level_df.loc[patient_level_df['age'] > 120]

,id1,gender,age,age_category,unit_category_ud,chronic_med_ud,response_reasons_other_text,dosing_frequency_sum,dosing_single_dose_sum,dosing_max_daily_dose_sum,neo_dosing_frequency_sum,neo_dosing_single_dose_sum,neo_dosing_max_daily_dose_sum,unique_hospitals,survival_rate_10y_age_adj_mean,charlson_score_age_adj_mean,hospital_days_mean,kidney_disease,hepatic_disease,diabetes_disease,ischemic_heart_disease,copd_disease,cerebrovascular_disease,peptic_ulcer_disease,dementia_disease,oncological_disease,hemato_oncological_disease,hypertension_disease,atrial_fibrillation_disease,hyperlipidemia_disease,congestive_heart_failure_disease,obesity_disease,atc_count_mean,chronic_drug_count_mean,diagnosis_count_mean,pvd_count_mean,pvd_group_count_mean,alerts_per_order_count_mean,chronic_med_count_mean,unit_Internal,unit_Surgery,unit_Gynecology,unit_Cardiology,unit_Emergency,unit_Internal-Covid19,unit_Geriatric,unit_Hematology,unit_Nephrology,unit_Oncology,is_Non_alert,is_Non_Error_alert,is_Error_Alert,is_No_response_need,is_Ignore,is_Change,liver_count_bool,hepatic_count_bool,cirrhosis_count_bool,hepatitis_count_bool,portal_hypertension_count_bool,jaundice_count_bool,myocardial_count_bool,heart_failure_count_bool,peripheral_vascular _disease_count_bool,cerebrovascular_count_bool,stroke_count_bool,cerebral_infarction_count_bool,tia_count_bool,cva_count_bool,dementia_count_bool,chronic_ pulmonary _disease_count_bool,copd_count_bool,chronic _obstructive _pulmonary _disease_count_bool,rheumatic_disease_count_bool,fibromyalgia_count_bool,gout_count_bool,arthritis_count_bool,ankylosing_spondylitis_count_bool,scleroderma_count_bool,duodenal_ulcer_count_bool,peptic_ulcer_count_bool,gastric_ulcer_count_bool,diabetes_count_bool,hemiplegia_count_bool,hemiparesis_count_bool,paraplegia_count_bool,renal_count_bool,pyelonephritis_count_bool,hemodialysis_count_bool,kidney_count_bool,ckd_count_bool,arf_count_bool,aki_count_bool,malignancy_count_bool,malignant_count_bool,carcinoma_count_bool,neoplasm_count_bool,adenocarcinoma_count_bool,leukemia_count_bool,aml_count_bool,cml_count_bool,lymphoma_count_bool,hiv_count_bool,metastatic_count_bool,metastasis_count_bool,liver_group_count_bool,cerebrovascular_group_count_bool,copd_group_count_bool,gout_group_count_bool,ulcer_group_count_bool,hemiplegia_group_count_bool,renal_group_count_bool,malignancy_group_count_bool,leukemia_group_count_bool,metastatic_group_count_bool
153274,265363,MALE,123.0,> 85,Surgery,0,NaN,0,0,0,0,0,0,1,53.39,4.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.333333,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,6,0,0,6,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
155265,268529,MALE,123.0,> 85,Surgery,0,NaN,0,0,0,0,0,0,1,53.39,4.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,4,0,0,4,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
155727,269546,FEMALE,123.0,> 85,new_internal,0,NaN,0,0,0,0,0,0,1,53.39,4.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,1,0,0,0,0,3,0,0,3,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [10]:
# Comprehensive TableOne with ALL continuous and categorical variables
# Overall summary (no grouping) - includes all variables

# Ensure all categorical columns are strings
for col in categorical_vars:
    if col in patient_level_df.columns:
        patient_level_df[col] = patient_level_df[col].astype(str)

# Binary variables that should show only "1" category
binary_vars = [col for col in categorical_vars if col.startswith('unit_') and col != 'unit_category_ud'] + \
              [col for col in categorical_vars if col.endswith('_disease')]

# Create comprehensive table with all variables
table_all = TableOne(
    patient_level_df,
    categorical=categorical_vars,
    continuous=continuous_vars,
    pval=False,  # No p-values needed for overall summary
    missing=False,  # Hide missing column
    overall=True  # Show overall column
)

# Filter the TableOne output: for binary variables, keep only category "1"
table_df = table_all.tableone

if table_df is not None and not table_df.empty and isinstance(table_df.index, pd.MultiIndex):
    # Build list of indices to keep
    keep_indices = []
    
    for idx in table_df.index:
        var_name_full = str(idx[0])  # e.g., 'unit_Internal, n (%)'
        category = str(idx[1]) if len(idx) > 1 else ""
        
        # Extract base variable name
        var_name_base = var_name_full.split(',')[0].strip()
        
        # Check if binary variable
        is_binary = var_name_base in binary_vars
        
        if not is_binary:
            # Keep all non-binary rows
            keep_indices.append(idx)
        elif is_binary and category.strip() == "1":
            # Keep only "1" category for binary variables
            keep_indices.append(idx)
        # Skip binary variables with category "0" or other values
    
    # Filter DataFrame
    table_filtered = table_df.loc[keep_indices]
    
    # Format and print
    print("=" * 80)
    print("COMPREHENSIVE DESCRIPTIVE STATISTICS - ALL VARIABLES")
    print("=" * 80)
    
    # Format output to match TableOne style
    from tabulate import tabulate
    
    output_rows = []
    for idx in table_filtered.index:
        var_name_full = str(idx[0])  # e.g., 'unit_Internal, n (%)'
        category = str(idx[1]) if len(idx) > 1 else ""
        overall_val = str(table_filtered.loc[idx, 'Overall'])
        
        if category == "":
            # Continuous variable or special row (like 'n')
            output_rows.append([var_name_full, "", overall_val])
        else:
            # Categorical variable with category
            # Show variable name on first row, category on second row (TableOne style)
            var_name_base = var_name_full.split(',')[0].strip()
            if var_name_base in binary_vars:
                # For binary variables, show: variable name row, then category "1" row
                output_rows.append([var_name_full, "", ""])  # Variable header
                output_rows.append(["", category, overall_val])  # Category "1" with value
            else:
                # Non-binary categorical (shouldn't be filtered, but handle)
                output_rows.append([var_name_full, "", ""])
                output_rows.append(["", category, overall_val])
    
    print(tabulate(output_rows, headers=["", "", "Overall"], tablefmt="pipe", showindex=False))
else:
    # Fallback
    print("=" * 80)
    print("COMPREHENSIVE DESCRIPTIVE STATISTICS - ALL VARIABLES")
    print("=" * 80)
    print(table_all.tabulate(tablefmt="pipe"))

================================================================================
COMPREHENSIVE DESCRIPTIVE STATISTICS - ALL VARIABLES
================================================================================
|                                           |              | Overall       |
|:------------------------------------------|:-------------|:--------------|
| n                                         |              | 155747        |
| gender, n (%)                             |              |               |
|                                           | FEMALE       | 84479 (54.2)  |
| gender, n (%)                             |              |               |
|                                           | MALE         | 71268 (45.8)  |
| age, mean (SD)                            |              | 56.9 (21.7)   |
| age_category, n (%)                       |              |               |
|                                           | 19-30        | 25389 (16.3)  |
| age_category, n (%)                       |              |               |
|                                           | 31-44        | 26837 (17.2)  |
| age_category, n (%)                       |              |               |
|                                           | 45-55        | 17947 (11.5)  |
| age_category, n (%)                       |              |               |
|                                           | 56-64        | 17921 (11.5)  |
| age_category, n (%)                       |              |               |
|                                           | 65-75        | 30613 (19.7)  |
| age_category, n (%)                       |              |               |
|                                           | 76-85        | 23257 (14.9)  |
| age_category, n (%)                       |              |               |
|                                           | > 85         | 13783 (8.8)   |
| unit_category_ud, n (%)                   |              |               |
|                                           | Emergency    | 20354 (13.1)  |
| unit_category_ud, n (%)                   |              |               |
|                                           | OTHER        | 22282 (14.3)  |
| unit_category_ud, n (%)                   |              |               |
|                                           | Surgery      | 49879 (32.0)  |
| unit_category_ud, n (%)                   |              |               |
|                                           | new_internal | 63232 (40.6)  |
| chronic_med_ud, n (%)                     |              |               |
|                                           | 0            | 125098 (80.3) |
| chronic_med_ud, n (%)                     |              |               |
|                                           | <5           | 8508 (5.5)    |
| chronic_med_ud, n (%)                     |              |               |
|                                           | >=5          | 22141 (14.2)  |
| survival_rate_10y_age_adj_mean, mean (SD) |              | 71.3 (34.9)   |
| charlson_score_age_adj_mean, mean (SD)    |              | 2.4 (2.6)     |
| hospital_days_mean, mean (SD)             |              | 2.8 (3.9)     |
| kidney_disease, n (%)                     |              |               |
|                                           | 1            | 7879 (5.1)    |
| hepatic_disease, n (%)                    |              |               |
|                                           | 1            | 2107 (1.4)    |
| diabetes_disease, n (%)                   |              |               |
|                                           | 1            | 22633 (14.5)  |
| ischemic_heart_disease, n (%)             |              |               |
|                                           | 1            | 11032 (7.1)   |
| copd_disease, n (%)                       |              |               |
|                                           | 1            | 3241 (2.1)    |
| cerebrovascular_disease, n (%)            |              |               |
|                                           | 1            | 27053 (17.4)  |
| peptic_ulcer_disease, n (%)               |              |               |
|                                           | 1            | 611 (0.4)     |
| dementia_disease, n (%)                   |              |               |
|                                           | 1            | 2052 (1.3)    |
| oncological_disease, n (%)                |              |               |
|                                           | 1            | 6081 (3.9)    |
| hemato_oncological_disease, n (%)         |              |               |
|                                           | 1            | 1146 (0.7)    |
| hypertension_disease, n (%)               |              |               |
|                                           | 1            | 34656 (22.3)  |
| atrial_fibrillation_disease, n (%)        |              |               |
|                                           | 1            | 7159 (4.6)    |
| hyperlipidemia_disease, n (%)             |              |               |
|                                           | 1            | 26463 (17.0)  |
| congestive_heart_failure_disease, n (%)   |              |               |
|                                           | 1            | 4199 (2.7)    |
| obesity_disease, n (%)                    |              |               |
|                                           | 1            | 9155 (5.9)    |
| diagnosis_count_mean, mean (SD)           |              | 1.9 (2.9)     |
| chronic_med_count_mean, mean (SD)         |              | 1.4 (2.7)     |
| unit_Internal, n (%)                      |              |               |
|                                           | 1            | 67459 (43.3)  |
| unit_Surgery, n (%)                       |              |               |
|                                           | 1            | 54637 (35.1)  |
| unit_Gynecology, n (%)                    |              |               |
|                                           | 1            | 18364 (11.8)  |
| unit_Cardiology, n (%)                    |              |               |
|                                           | 1            | 6109 (3.9)    |
| unit_Emergency, n (%)                     |              |               |
|                                           | 1            | 29623 (19.0)  |
| unit_Internal-Covid19, n (%)              |              |               |
|                                           | 1            | 4346 (2.8)    |
| unit_Geriatric, n (%)                     |              |               |
|                                           | 1            | 890 (0.6)     |
| unit_Hematology, n (%)                    |              |               |
|                                           | 1            | 335 (0.2)     |
| unit_Nephrology, n (%)                    |              |               |
|                                           | 1            | 929 (0.6)     |
| unit_Oncology, n (%)                      |              |               |
|                                           | 1            | 120 (0.1)     |

✅ Drop-in function to clean TableOne output

In [19]:
import pandas as pd
import numpy as np
from tableone import TableOne

def clean_tableone_for_article(tableone_obj,
                               binary_vars=None,
                               drop_groupby_var="gender",
                               keep_binary_level="1"):
    t = tableone_obj.tableone.copy()

    # 1) Fix MultiIndex rows -> columns
    if isinstance(t.index, pd.MultiIndex):
        t = t.reset_index()
        t.columns = ["RowName", "Level"] + list(t.columns[2:])
    else:
        t = t.reset_index().rename(columns={"index": "RowName"})
        if "Level" not in t.columns:
            t["Level"] = ""

    # 2) Create clean Variable name (remove ", n (%)" / ", mean (SD)" etc.)
    t["Variable"] = t["RowName"].astype(str).str.split(",").str[0].str.strip()

    # 3) Clean Level column
    t["Level"] = t["Level"].astype(str).str.strip()
    t.loc[t["Level"].isin(["nan", "None"]), "Level"] = ""

    # 4) Filter binary variables: keep only level "1"
    if binary_vars:
        is_binary = t["Variable"].isin(binary_vars)
        t = t.loc[~is_binary | (t["Level"] == keep_binary_level)].copy()

    # 5) Drop grouping variable block (gender rows) - usually not needed
    if drop_groupby_var:
        t = t.loc[t["Variable"].str.lower() != drop_groupby_var.lower()].copy()

    # 6) Clean column names (group labels / p-value)
    # Sometimes TableOne makes MultiIndex columns; handle both cases:
    if isinstance(t.columns, pd.MultiIndex):
        t.columns = [c[1] if c[1] else c[0] for c in t.columns]

    # Normalize common column names
    t.columns = [str(c).strip() for c in t.columns]  # fixes "MALE " -> "MALE"
    rename_cols = {"P-Value": "P-value", "P-value": "P-value"}
    t = t.rename(columns=rename_cols)

    # 7) Put Variable/Level first
    front = ["Variable", "Level"]
    rest = [c for c in t.columns if c not in front and c not in ["RowName"]]
    t = t[front + rest]

    return t

✅ Use it in your workflow (minimal changes)

In [20]:
# Build TableOne
table_all_by_gender = TableOne(
    patient_level_df,
    categorical=categorical_vars,
    continuous=continuous_vars,
    groupby="gender",
    pval=True,
    missing=False,
    overall=True
)

# Define binary vars as you did
binary_vars = [col for col in categorical_vars if col.startswith('unit_') and col != 'unit_category_ud'] + \
              [col for col in categorical_vars if col.endswith('_disease')]

# Clean output
table_df_clean = clean_tableone_for_article(
    table_all_by_gender,
    binary_vars=binary_vars,
    drop_groupby_var="gender",   # remove gender rows (recommended)
    keep_binary_level="1"
)

# Print nice preview
from tabulate import tabulate
print(tabulate(table_df_clean.head(40), headers="keys", tablefmt="pipe", showindex=False))

| Variable                         | Level        | ('Grouped by gender', 'Overall')   | ('Grouped by gender', 'FEMALE')   | ('Grouped by gender', 'MALE ')   | ('Grouped by gender', 'P-Value')   |
|:---------------------------------|:-------------|:-----------------------------------|:----------------------------------|:---------------------------------|:-----------------------------------|
| n                                |              | 155747                             | 84479                             | 71268                            |                                    |
| age                              |              | 56.9 (21.7)                        | 54.6 (22.8)                       | 59.6 (20.0)                      | <0.001                             |
| age_category                     | 19-30        | 25389 (16.3)                       | 17223 (20.4)                      | 8166 (11.5)                      | <0.001                             |
| age_category                     | 31-44        | 26837 (17.2)                       | 17305 (20.5)                      | 9532 (13.4)                      |                                    |
| age_category                     | 45-55        | 17947 (11.5)                       | 8272 (9.8)                        | 9675 (13.6)                      |                                    |
| age_category                     | 56-64        | 17921 (11.5)                       | 7796 (9.2)                        | 10125 (14.2)                     |                                    |
| age_category                     | 65-75        | 30613 (19.7)                       | 13938 (16.5)                      | 16675 (23.4)                     |                                    |
| age_category                     | 76-85        | 23257 (14.9)                       | 11909 (14.1)                      | 11348 (15.9)                     |                                    |
| age_category                     | > 85         | 13783 (8.8)                        | 8036 (9.5)                        | 5747 (8.1)                       |                                    |
| unit_category_ud                 | Emergency    | 20354 (13.1)                       | 13171 (15.6)                      | 7183 (10.1)                      | <0.001                             |
| unit_category_ud                 | OTHER        | 22282 (14.3)                       | 18468 (21.9)                      | 3814 (5.4)                       |                                    |
| unit_category_ud                 | Surgery      | 49879 (32.0)                       | 21854 (25.9)                      | 28025 (39.3)                     |                                    |
| unit_category_ud                 | new_internal | 63232 (40.6)                       | 30986 (36.7)                      | 32246 (45.2)                     |                                    |
| chronic_med_ud                   | 0            | 125098 (80.3)                      | 70709 (83.7)                      | 54389 (76.3)                     | <0.001                             |
| chronic_med_ud                   | <5           | 8508 (5.5)                         | 3886 (4.6)                        | 4622 (6.5)                       |                                    |
| chronic_med_ud                   | >=5          | 22141 (14.2)                       | 9884 (11.7)                       | 12257 (17.2)                     |                                    |
| survival_rate_10y_age_adj_mean   |              | 71.3 (34.9)                        | 74.1 (33.8)                       | 68.0 (35.9)                      | <0.001                             |
| charlson_score_age_adj_mean      |              | 2.4 (2.6)                          | 2.2 (2.5)                         | 2.8 (2.6)                        | <0.001                             |
| hospital_days_mean               |              | 2.8 (3.9)                          | 2.6 (3.6)                         | 3.0 (4.3)                        | <0.001                             |
| kidney_disease                   | 1            | 7879 (5.1)                         | 2902 (3.4)                        | 4977 (7.0)                       |                                    |
| hepatic_disease                  | 1            | 2107 (1.4)                         | 1122 (1.3)                        | 985 (1.4)                        |                                    |
| diabetes_disease                 | 1            | 22633 (14.5)                       | 10469 (12.4)                      | 12164 (17.1)                     |                                    |
| ischemic_heart_disease           | 1            | 11032 (7.1)                        | 2820 (3.3)                        | 8212 (11.5)                      |                                    |
| copd_disease                     | 1            | 3241 (2.1)                         | 1107 (1.3)                        | 2134 (3.0)                       |                                    |
| cerebrovascular_disease          | 1            | 27053 (17.4)                       | 12858 (15.2)                      | 14195 (19.9)                     |                                    |
| peptic_ulcer_disease             | 1            | 611 (0.4)                          | 229 (0.3)                         | 382 (0.5)                        |                                    |
| dementia_disease                 | 1            | 2052 (1.3)                         | 1291 (1.5)                        | 761 (1.1)                        |                                    |
| oncological_disease              | 1            | 6081 (3.9)                         | 2967 (3.5)                        | 3114 (4.4)                       |                                    |
| hemato_oncological_disease       | 1            | 1146 (0.7)                         | 503 (0.6)                         | 643 (0.9)                        |                                    |
| hypertension_disease             | 1            | 34656 (22.3)                       | 16686 (19.8)                      | 17970 (25.2)                     |                                    |
| atrial_fibrillation_disease      | 1            | 7159 (4.6)                         | 3607 (4.3)                        | 3552 (5.0)                       |                                    |
| hyperlipidemia_disease           | 1            | 26463 (17.0)                       | 11776 (13.9)                      | 14687 (20.6)                     |                                    |
| congestive_heart_failure_disease | 1            | 4199 (2.7)                         | 1743 (2.1)                        | 2456 (3.4)                       |                                    |
| obesity_disease                  | 1            | 9155 (5.9)                         | 5120 (6.1)                        | 4035 (5.7)                       |                                    |
| diagnosis_count_mean             |              | 1.9 (2.9)                          | 1.6 (2.8)                         | 2.2 (3.1)                        | <0.001                             |
| chronic_med_count_mean           |              | 1.4 (2.7)                          | 1.2 (2.5)                         | 1.8 (2.9)                        | <0.001                             |
| unit_Internal                    | 1            | 67459 (43.3)                       | 32637 (38.6)                      | 34822 (48.9)                     |                                    |
| unit_Surgery                     | 1            | 54637 (35.1)                       | 24011 (28.4)                      | 30626 (43.0)                     |                                    |
| unit_Gynecology                  | 1            | 18364 (11.8)                       | 18364 (21.7)                      | 0 (0.0)                          |                                    |
| unit_Cardiology                  | 1            | 6109 (3.9)                         | 1770 (2.1)                        | 4339 (6.1)                       |                                    |

✅ Save to Excel/CSV (clean version)

In [22]:
output_dir = "output"
import os
os.makedirs(output_dir, exist_ok=True)

#table_df_clean.to_csv(os.path.join(output_dir, "table_one_by_gender_clean.csv"), index=False)
table_df_clean.to_excel(os.path.join(output_dir, "table_one_by_gender_clean.xlsx"), index=False)